[toolchain]
channel = "1.68.0"
#channel = "nightly-2023-01-20"
components = [ "rustc", "rust-std", "cargo", "rustfmt", "rustc-dev", "llvm-tools-preview" ] # TODO llvm-tools-preview may be unnecessary
