[book]
language = "en"
src = "src"
title = "Verus Tutorial and Reference"

[rust]
edition = "2018"

[output.html]
smart-punctuation = true

[output.html.playground]
runnable = false

[preprocessor.verus-grammar]
command = "python3 verus-grammar.py"

[preprocessor.custom-admonitions]
command = "python3 custom-admonitions.py"
