use crate::metadata::{PackageMetadata, PackageSource};

pub type Toolchain = cargo_verus_toolchains::Toolchain<&'static str>;
pub type Crate = cargo_verus_toolchains::Crate<&'static str>;

pub fn is_matching_known_and_used(known: &Crate, used: &PackageMetadata) -> bool {
    match (known, &used.source) {
        (Crate::Registry(known_version), PackageSource::Registry { .. }) => {
            known_version == &used.version.to_string()
        }
        (
            Crate::GitCommit { git: known_url, rev: known_rev },
            PackageSource::Git { url: ref used_url, rev: Some(ref used_rev) },
        ) => known_url == used_url && known_rev == used_rev,
        _ => false,
    }
}

include!(
    // Points to a file generated by `build.rs`.
    concat!(env!("OUT_DIR"), "/toolchain_list.rs")
);
