use std::path::Path;

use anyhow::{Context, Result, bail};

use crate::metadata::{PackageMetadata, PackageSource};

pub type Toolchain = cargo_verus_toolchains::Toolchain<&'static str>;
pub type Crate = cargo_verus_toolchains::Crate<&'static str>;

/// Find the known toolchain for a Verus version reported by `verus --version`.
pub fn find_toolchain(verus_version: &str) -> Option<&'static Toolchain> {
    TOOLCHAINS.iter().find(|toolchain| toolchain.verus == verus_version)
}

/// Check whether a known toolchain component (e.g. `vstd`) matches a dependency used by Cargo.
pub fn is_matching_known_and_used(known: &Crate, used: &PackageMetadata) -> bool {
    match (known, &used.source) {
        (Crate::Registry(known_version), PackageSource::Registry { .. }) => {
            known_version == &used.version.to_string()
        }
        (
            Crate::GitCommit { git: known_url, rev: known_rev },
            PackageSource::Git { url: used_url, rev: Some(used_rev) },
        ) => known_url == used_url && known_rev == used_rev,
        _ => false,
    }
}

/// Resolve the `vstd` dependency to use based on the Verus version.
pub fn infer_vstd_dependency(verus_version: &str, vstd_source_dir: &Path) -> Result<String> {
    if verus_version.strip_suffix(".dirty").is_some() {
        let vstd_source_dir = vstd_source_dir.canonicalize().context(format!(
            "resolving in-tree vstd source directory `{}` for dirty Verus version {verus_version}",
            vstd_source_dir.display()
        ))?;
        let manifest = vstd_source_dir.join("Cargo.toml");
        if !manifest.is_file() {
            bail!(
                "in-tree vstd source directory `{}` for dirty Verus version {verus_version} has no Cargo.toml",
                vstd_source_dir.display()
            );
        }
        let path = serde_json::to_string(&vstd_source_dir.to_string_lossy())?;
        return Ok(format!("{{ path = {path} }}"));
    }

    let toolchain = find_toolchain(verus_version).context(format!(
        "no known toolchain manifest for Verus version {verus_version}; cannot determine the vstd dependency"
    ))?;
    Ok(format_known_dependency(&toolchain.vstd))
}

fn format_known_dependency(vstd: &Crate) -> String {
    match vstd {
        Crate::Registry(version) => {
            serde_json::to_string(&format!("={version}")).expect("serializing a string")
        }
        Crate::GitCommit { git, rev } => {
            let git = serde_json::to_string(git).expect("serializing a string");
            let rev = serde_json::to_string(rev).expect("serializing a string");
            format!("{{ git = {git}, rev = {rev} }}")
        }
    }
}

include!(
    // Points to a file generated by `build.rs`.
    concat!(env!("OUT_DIR"), "/toolchain_list.rs")
);

#[cfg(test)]
mod tests {
    use super::{
        Crate, TOOLCHAINS, find_toolchain, format_known_dependency, infer_vstd_dependency,
    };

    #[test]
    fn finds_each_known_toolchain_by_verus_version() {
        for toolchain in TOOLCHAINS {
            let found = find_toolchain(toolchain.verus).expect("known toolchain should be found");
            assert_eq!(found, &toolchain);
        }
    }

    #[test]
    fn does_not_find_an_unknown_toolchain() {
        assert!(find_toolchain("0.0.0.unknown").is_none());
    }

    #[test]
    fn clean_version_uses_its_manifest_dependency() {
        let toolchain = TOOLCHAINS.first().expect("at least one toolchain");
        let observed = infer_vstd_dependency(toolchain.verus, std::path::Path::new("unused"))
            .expect("resolve clean version");

        assert_eq!(observed, format_known_dependency(&toolchain.vstd));
    }

    #[test]
    fn formats_registry_vstd_as_an_exact_version() {
        assert_eq!(format_known_dependency(&Crate::Registry("1.2.3")), r#""=1.2.3""#);
    }

    #[test]
    fn formats_git_vstd_as_a_git_dependency() {
        assert_eq!(
            format_known_dependency(&Crate::GitCommit {
                git: "https://example.test/verus.git",
                rev: "abc123"
            }),
            r#"{ git = "https://example.test/verus.git", rev = "abc123" }"#
        );
    }

    #[test]
    fn dirty_version_uses_the_in_tree_vstd_path() {
        let temp_dir = tempfile::tempdir().expect("create temp dir");
        let vstd_dir = temp_dir.path().join("vstd");
        std::fs::create_dir(&vstd_dir).expect("create vstd dir");
        std::fs::write(
            vstd_dir.join("Cargo.toml"),
            r#"
[package]
name = "vstd"
"#,
        )
        .expect("write vstd manifest");

        let observed = infer_vstd_dependency("0.2026.08.23.fbbbbcf.dirty", &vstd_dir)
            .expect("resolve dirty version");
        let expected_path = vstd_dir.canonicalize().expect("canonicalize vstd dir");
        let expected_path =
            serde_json::to_string(&expected_path.to_string_lossy()).expect("serialize path");
        assert_eq!(observed, format!("{{ path = {expected_path} }}"));
    }

    #[test]
    fn unknown_clean_version_is_rejected() {
        let error = infer_vstd_dependency("0.0.0.unknown", std::path::Path::new("unused"))
            .expect_err("unknown version should fail");
        assert!(error.to_string().contains("no known toolchain manifest"));
    }
}
