[package]
name = "qi-graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive", "rc"] }
bincode = "1.3"
getopts = "*"
petgraph = "0.5.1"
serde_json = { version = "1", features = ["preserve_order"] }
internals_interface = { path = "../internals_interface" }