sed -i '.bak' -e 's/\\bmap_axioms\\b/\\bgroup_map_axioms\\b/g' *.rs
sed -i '.bak' -e 's/\\bseq_lib_default\\b/\\bgroup_seq_lib_default\\b/g' *.rs
sed -i '.bak' -e 's/\\bbits_axioms\\b/\\bgroup_bits_axioms\\b/g' *.rs
sed -i '.bak' -e 's/\\bvec_axioms\\b/\\bgroup_vec_axioms\\b/g' *.rs
sed -i '.bak' -e 's/\\brange_axioms\\b/\\bgroup_range_axioms\\b/g' *.rs
sed -i '.bak' -e 's/\\bcontrol_flow_axioms\\b/\\bgroup_control_flow_axioms\\b/g' *.rs
sed -i '.bak' -e 's/\\bmul_basics\\b/\\bgroup_mul_basics\\b/g' *.rs
sed -i '.bak' -e 's/\\bmul_is_distributive\\b/\\bgroup_mul_is_distributive\\b/g' *.rs
sed -i '.bak' -e 's/\\bmul_is_commutative_and_distributive\\b/\\bgroup_mul_is_commutative_and_distributive\\b/g' *.rs
sed -i '.bak' -e 's/\\bmul_properties\\b/\\bgroup_mul_properties\\b/g' *.rs
sed -i '.bak' -e 's/\\bprovides\\b/\\bgroup_provides\\b/g' *.rs
sed -i '.bak' -e 's/\\bdiv_basics\\b/\\bgroup_div_basics\\b/g' *.rs
sed -i '.bak' -e 's/\\bprovides\\b/\\bgroup_provides\\b/g' *.rs
sed -i '.bak' -e 's/\\bmod_basics\\b/\\bgroup_mod_basics\\b/g' *.rs
sed -i '.bak' -e 's/\\bmod_properties\\b/\\bgroup_mod_properties\\b/g' *.rs
sed -i '.bak' -e 's/\\bprovides\\b/\\bgroup_provides\\b/g' *.rs
sed -i '.bak' -e 's/\\bfundamental_div_mod_converse\\b/\\bgroup_fundamental_div_mod_converse\\b/g' *.rs
sed -i '.bak' -e 's/\\bprovides\\b/\\bgroup_provides\\b/g' *.rs
sed -i '.bak' -e 's/\\bmul_properties_internal\\b/\\bgroup_mul_properties_internal\\b/g' *.rs
sed -i '.bak' -e 's/\\bprovides\\b/\\bgroup_provides\\b/g' *.rs
sed -i '.bak' -e 's/\\bpow_properties\\b/\\bgroup_pow_properties\\b/g' *.rs
sed -i '.bak' -e 's/\\barray_axioms\\b/\\bgroup_array_axioms\\b/g' *.rs
sed -i '.bak' -e 's/\\bset_axioms\\b/\\bgroup_set_axioms\\b/g' *.rs
sed -i '.bak' -e 's/\\bstring_axioms\\b/\\bgroup_string_axioms\\b/g' *.rs
sed -i '.bak' -e 's/\\bptr_axioms\\b/\\bgroup_ptr_axioms\\b/g' *.rs
sed -i '.bak' -e 's/\\bmultiset_axioms\\b/\\bgroup_multiset_axioms\\b/g' *.rs
sed -i '.bak' -e 's/\\bseq_axioms\\b/\\bgroup_seq_axioms\\b/g' *.rs
sed -i '.bak' -e 's/\\bvstd_default\\b/\\bgroup_vstd_default\\b/g' *.rs
sed -i '.bak' -e 's/\\bvstd_default\\b/\\bgroup_vstd_default\\b/g' *.rs
sed -i '.bak' -e 's/\\bset_lib_axioms\\b/\\bgroup_set_lib_axioms\\b/g' *.rs
