[package]
name = "verus"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.7.4"
zip = "0.6.6"
chrono = "0.4.26"
yansi = "0.5"
serde_json = "1.0"
regex = "1"

[target."cfg(windows)".dependencies]
win32job = "1"

[build_dependencies]
regex = "1"