use crate::rust_to_vir_base::ident_to_var;
use crate::util::{err_span_str, err_span_string};
use rustc_ast::token::{Token, TokenKind};
use rustc_ast::tokenstream::{TokenStream, TokenTree};
use rustc_ast::{AttrKind, Attribute, MacArgs};
use rustc_span::Span;
use vir::ast::{Mode, TriggerAnnotation, VirErr};

#[derive(Debug)]
pub(crate) enum AttrTree {
    Fun(Span, String, Option<Box<[AttrTree]>>),
    Eq(Span, String, String),
}

pub(crate) fn token_to_string(token: &Token) -> Result<Option<String>, ()> {
    match token.kind {
        TokenKind::Literal(lit) => Ok(Some(lit.symbol.as_str().to_string())),
        TokenKind::Ident(symbol, _) => Ok(Some(symbol.as_str().to_string())),
        TokenKind::Comma => Ok(None),
        _ => Err(()),
    }
}

pub(crate) fn token_stream_to_trees(
    span: Span,
    stream: &TokenStream,
) -> Result<Box<[AttrTree]>, ()> {
    let mut token_trees: Vec<TokenTree> = Vec::new();
    for x in stream.trees() {
        token_trees.push(x);
    }
    let mut i = 0;
    let mut trees: Vec<AttrTree> = Vec::new();
    while i < token_trees.len() {
        match &token_trees[i] {
            TokenTree::Token(token) => {
                if let Some(name) = token_to_string(token)? {
                    let fargs = if i + 1 < token_trees.len() {
                        if let TokenTree::Delimited(_, _, token_stream) = &token_trees[i + 1] {
                            i += 1;
                            Some(token_stream_to_trees(span, token_stream)?)
                        } else {
                            None
                        }
                    } else {
                        None
                    };
                    trees.push(AttrTree::Fun(span, name, fargs));
                }
                i += 1;
            }
            _ => return Err(()),
        }
    }
    Ok(trees.into_boxed_slice())
}

pub(crate) fn mac_args_to_tree(span: Span, name: String, args: &MacArgs) -> Result<AttrTree, ()> {
    match args {
        MacArgs::Empty => Ok(AttrTree::Fun(span, name, None)),
        MacArgs::Delimited(_, _, token_stream) => {
            Ok(AttrTree::Fun(span, name, Some(token_stream_to_trees(span, token_stream)?)))
        }
        MacArgs::Eq(_, token) => match token_to_string(token)? {
            None => Err(()),
            Some(token) => Ok(AttrTree::Eq(span, name, token)),
        },
    }
}

pub(crate) fn attr_to_tree(attr: &Attribute) -> Result<AttrTree, ()> {
    match &attr.kind {
        AttrKind::Normal(item, _) => match &item.path.segments[..] {
            [segment] => {
                let name = ident_to_var(&segment.ident).as_str().to_string();
                mac_args_to_tree(attr.span, name, &item.args)
            }
            _ => Err(()),
        },
        _ => Err(()),
    }
}

pub(crate) fn attrs_to_trees(attrs: &[Attribute]) -> Vec<AttrTree> {
    let mut attr_trees: Vec<AttrTree> = Vec::new();
    for attr in attrs {
        if let Ok(tree) = attr_to_tree(attr) {
            attr_trees.push(tree);
        }
    }
    attr_trees
}

#[derive(Debug)]
pub(crate) enum GetVariantField {
    Named(String),
    Unnamed(usize),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum GhostBlockAttr {
    Proof,
    GhostWrapped,
    TrackedWrapped,
    Tracked,
    Wrapper,
}

pub(crate) enum Attr {
    // specify mode (spec, proof, exec)
    Mode(Mode),
    // function return mode (spec, proof, exec)
    ReturnMode(Mode),
    // generated by verus! macro
    VerusMacro,
    // parse function to get header, but don't verify body
    ExternalBody,
    // don't parse function; function can't be called directly from verified code
    External,
    // hide body (from all modules) until revealed
    Opaque,
    // publish body
    Publish,
    // publish body with zero fuel
    OpaqueOutsideModule,
    // Rust ghost block
    GhostBlock(GhostBlockAttr),
    // type parameter is not necessarily used in strictly positive positions
    MaybeNegative,
    // type parameter is used in strictly positive positions
    StrictlyPositive,
    // export function's require/ensure as global forall
    BroadcastForall,
    // accept the trigger chosen by triggers_auto without printing any diagnostics
    AutoTrigger,
    // exclude a particular function from being chosen in a trigger by triggers_auto
    NoAutoTrigger,
    // when used in a spec context, promote to spec by inserting .view()
    Autoview,
    // add manual trigger to expression inside quantifier
    Trigger(Option<Vec<u64>>),
    // custom error string to report for precondition failures
    CustomReqErr(String),
    // custom error string to report for precondition failures for a specific precondition
    CustomReqErrIdx(String, usize),
    // verify using bitvector theory
    BitVector,
    // for unforgeable token types
    Unforgeable,
    // for 'atomic' operations (e.g., CAS)
    Atomic,
    // specifies an invariant block
    InvariantBlock,
    // an enum variant is_Variant
    IsVariant(String),
    // an enum variant get_Variant
    GetVariant(String, GetVariantField),
    // this proof function is a termination proof
    DecreasesBy,
    // in a spec function, check the body for violations of recommends
    CheckRecommends,
    // set smt.arith.nl=true
    NonLinear,
    // verify non linear arithmetic using Singular
    IntegerRing,
    // Use a new dedicated Z3 process just for this query
    SpinoffProver,
}

fn get_trigger_arg(span: Span, attr_tree: &AttrTree) -> Result<u64, VirErr> {
    let i = match attr_tree {
        AttrTree::Fun(_, name, None) => match name.parse::<u64>() {
            Ok(i) => Some(i),
            _ => None,
        },
        _ => None,
    };
    match i {
        Some(i) => Ok(i),
        None => err_span_string(span, format!("expected integer constant, found {:?}", &attr_tree)),
    }
}

pub(crate) fn parse_attrs(attrs: &[Attribute]) -> Result<Vec<Attr>, VirErr> {
    let mut v: Vec<Attr> = Vec::new();
    for attr in attrs_to_trees(attrs) {
        match &attr {
            AttrTree::Fun(_, name, None) if name == "spec" => v.push(Attr::Mode(Mode::Spec)),
            AttrTree::Fun(_, name, Some(box [AttrTree::Fun(_, arg, None)]))
                if name == "spec" && arg == "checked" =>
            {
                v.push(Attr::Mode(Mode::Spec));
                v.push(Attr::CheckRecommends);
            }
            AttrTree::Fun(_, name, None) if name == "proof" => v.push(Attr::Mode(Mode::Proof)),
            AttrTree::Fun(_, name, None) if name == "exec" => v.push(Attr::Mode(Mode::Exec)),
            AttrTree::Fun(_, name, None) if name == "trigger" => v.push(Attr::Trigger(None)),
            AttrTree::Fun(span, name, Some(args)) if name == "trigger" => {
                let mut groups: Vec<u64> = Vec::new();
                for arg in args.iter() {
                    groups.push(get_trigger_arg(*span, arg)?);
                }
                if groups.len() == 0 {
                    return err_span_str(
                        *span,
                        "expected either #[trigger] or non-empty #[trigger(...)]",
                    );
                }
                v.push(Attr::Trigger(Some(groups)));
            }
            AttrTree::Fun(_, name, None) if name == "auto_trigger" => v.push(Attr::AutoTrigger),
            AttrTree::Fun(span, name, args) if name == "verifier" => match &args {
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "verus_macro" => {
                    v.push(Attr::VerusMacro)
                }
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "external_body" => {
                    v.push(Attr::ExternalBody)
                }
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "external" => {
                    v.push(Attr::External)
                }
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "opaque" => v.push(Attr::Opaque),
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "publish" => {
                    v.push(Attr::Publish)
                }
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "opaque_outside_module" => {
                    v.push(Attr::OpaqueOutsideModule)
                }
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "proof_block" => {
                    v.push(Attr::GhostBlock(GhostBlockAttr::Proof))
                }
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "ghost_block_wrapped" => {
                    v.push(Attr::GhostBlock(GhostBlockAttr::GhostWrapped))
                }
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "tracked_block_wrapped" => {
                    v.push(Attr::GhostBlock(GhostBlockAttr::TrackedWrapped))
                }
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "tracked_block" => {
                    v.push(Attr::GhostBlock(GhostBlockAttr::Tracked))
                }
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "ghost_wrapper" => {
                    v.push(Attr::GhostBlock(GhostBlockAttr::Wrapper))
                }
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "maybe_negative" => {
                    v.push(Attr::MaybeNegative)
                }
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "strictly_positive" => {
                    v.push(Attr::StrictlyPositive)
                }
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "broadcast_forall" => {
                    v.push(Attr::BroadcastForall)
                }
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "no_auto_trigger" => {
                    v.push(Attr::NoAutoTrigger)
                }
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "autoview" => {
                    v.push(Attr::Autoview)
                }
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "unforgeable" => {
                    v.push(Attr::Unforgeable)
                }
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "atomic" => v.push(Attr::Atomic),
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "invariant_block" => {
                    v.push(Attr::InvariantBlock)
                }
                Some(box [AttrTree::Fun(_, arg, Some(box [AttrTree::Fun(_, ident, None)]))])
                    if arg == "is_variant" =>
                {
                    v.push(Attr::IsVariant(ident.clone()))
                }
                Some(
                    box [
                        AttrTree::Fun(
                            _,
                            arg,
                            Some(
                                box [
                                    AttrTree::Fun(_, variant_ident, None),
                                    AttrTree::Fun(_, field_ident, None),
                                ],
                            ),
                        ),
                    ],
                ) if arg == "get_variant" => {
                    let field_ident = match field_ident.parse::<usize>().ok() {
                        Some(i) => GetVariantField::Unnamed(i),
                        None => GetVariantField::Named(field_ident.clone()),
                    };
                    v.push(Attr::GetVariant(variant_ident.clone(), field_ident))
                }
                Some(box [AttrTree::Fun(_, arg, Some(box [AttrTree::Fun(_, msg, None)]))])
                    if arg == "custom_req_err" =>
                {
                    v.push(Attr::CustomReqErr(msg.clone()))
                }
                Some(
                    box [
                        AttrTree::Fun(
                            span,
                            arg,
                            Some(box [AttrTree::Fun(_, msg, None), AttrTree::Fun(_, idx, None)]),
                        ),
                    ],
                ) if arg == "custom_req_err" => match idx.parse::<usize>() {
                    Err(_) => {
                        return err_span_string(
                            span.clone(),
                            format!("expected integer constant as second argument"),
                        );
                    }
                    Ok(i) => {
                        v.push(Attr::CustomReqErrIdx(msg.clone(), i));
                    }
                },
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "bit_vector" => {
                    v.push(Attr::BitVector)
                }
                Some(box [AttrTree::Fun(_, arg, None)])
                    if arg == "decreases_by" || arg == "recommends_by" =>
                {
                    v.push(Attr::DecreasesBy)
                }
                Some(box [AttrTree::Fun(_, arg, Some(box [AttrTree::Fun(_, name, None)]))])
                    if arg == "returns" && name == "spec" =>
                {
                    v.push(Attr::ReturnMode(Mode::Spec))
                }
                Some(box [AttrTree::Fun(_, arg, Some(box [AttrTree::Fun(_, name, None)]))])
                    if arg == "returns" && name == "proof" =>
                {
                    v.push(Attr::ReturnMode(Mode::Proof))
                }
                Some(box [AttrTree::Fun(_, arg, Some(box [AttrTree::Fun(_, name, None)]))])
                    if arg == "returns" && name == "exec" =>
                {
                    v.push(Attr::ReturnMode(Mode::Exec))
                }
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "integer_ring" => {
                    v.push(Attr::IntegerRing)
                }
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "nonlinear" => {
                    v.push(Attr::NonLinear)
                }
                Some(box [AttrTree::Fun(_, arg, None)]) if arg == "spinoff_prover" => {
                    v.push(Attr::SpinoffProver)
                }
                _ => return err_span_str(*span, "unrecognized verifier attribute"),
            },
            _ => {}
        }
    }
    Ok(v)
}

pub(crate) fn parse_attrs_opt(attrs: &[Attribute]) -> Vec<Attr> {
    match parse_attrs(attrs) {
        Ok(attrs) => attrs,
        Err(_) => vec![],
    }
}

pub(crate) fn get_ghost_block_opt(attrs: &[Attribute]) -> Option<GhostBlockAttr> {
    for attr in parse_attrs_opt(attrs) {
        match attr {
            Attr::GhostBlock(g) => return Some(g),
            _ => {}
        }
    }
    None
}

pub(crate) fn get_mode_opt(attrs: &[Attribute]) -> Option<Mode> {
    for attr in parse_attrs_opt(attrs) {
        match attr {
            Attr::Mode(m) => return Some(m),
            _ => {}
        }
    }
    None
}

pub(crate) fn get_mode(default_mode: Mode, attrs: &[Attribute]) -> Mode {
    get_mode_opt(attrs).unwrap_or(default_mode)
}

pub(crate) fn get_var_mode(function_mode: Mode, attrs: &[Attribute]) -> Mode {
    let default_mode = if function_mode == Mode::Proof { Mode::Spec } else { function_mode };
    get_mode(default_mode, attrs)
}

pub(crate) fn get_ret_mode(function_mode: Mode, attrs: &[Attribute]) -> Mode {
    let mut mode = get_var_mode(function_mode, &[]);
    for attr in parse_attrs_opt(attrs) {
        match attr {
            Attr::ReturnMode(m) => mode = m,
            _ => {}
        }
    }
    mode
}

pub(crate) fn get_trigger(attrs: &[Attribute]) -> Result<Vec<TriggerAnnotation>, VirErr> {
    let mut groups: Vec<TriggerAnnotation> = Vec::new();
    for attr in parse_attrs(attrs)? {
        match attr {
            Attr::AutoTrigger => groups.push(TriggerAnnotation::AutoTrigger),
            Attr::Trigger(None) => groups.push(TriggerAnnotation::Trigger(None)),
            Attr::Trigger(Some(group_ids)) => {
                groups.extend(group_ids.into_iter().map(|id| TriggerAnnotation::Trigger(Some(id))));
            }
            _ => {}
        }
    }
    Ok(groups)
}

pub(crate) fn get_fuel(vattrs: &VerifierAttrs) -> u32 {
    if vattrs.opaque { 0 } else { 1 }
}

pub(crate) fn get_publish(vattrs: &VerifierAttrs) -> Option<bool> {
    match (vattrs.publish, vattrs.opaque_outside_module) {
        (false, _) => None,
        (true, false) => Some(true),
        (true, true) => Some(false),
    }
}

#[derive(Debug)]
pub(crate) struct VerifierAttrs {
    pub(crate) verus_macro: bool,
    pub(crate) external_body: bool,
    pub(crate) external: bool,
    pub(crate) opaque: bool,
    pub(crate) publish: bool,
    pub(crate) opaque_outside_module: bool,
    pub(crate) strictly_positive: bool,
    pub(crate) maybe_negative: bool,
    pub(crate) broadcast_forall: bool,
    pub(crate) no_auto_trigger: bool,
    pub(crate) autoview: bool,
    pub(crate) custom_req_err_main: Option<String>,
    pub(crate) custom_req_err_idxs: Vec<(String, usize)>,
    pub(crate) bit_vector: bool,
    pub(crate) unforgeable: bool,
    pub(crate) atomic: bool,
    pub(crate) integer_ring: bool,
    pub(crate) is_variant: Option<String>,
    pub(crate) get_variant: Option<(String, GetVariantField)>,
    pub(crate) decreases_by: bool,
    pub(crate) check_recommends: bool,
    pub(crate) nonlinear: bool,
    pub(crate) spinoff_prover: bool,
}

pub(crate) fn get_verifier_attrs(attrs: &[Attribute]) -> Result<VerifierAttrs, VirErr> {
    let mut vs = VerifierAttrs {
        verus_macro: false,
        external_body: false,
        external: false,
        opaque: false,
        publish: false,
        opaque_outside_module: false,
        maybe_negative: false,
        strictly_positive: false,
        broadcast_forall: false,
        no_auto_trigger: false,
        autoview: false,
        custom_req_err_main: None,
        custom_req_err_idxs: vec![],
        bit_vector: false,
        unforgeable: false,
        atomic: false,
        integer_ring: false,
        is_variant: None,
        get_variant: None,
        decreases_by: false,
        check_recommends: false,
        nonlinear: false,
        spinoff_prover: false,
    };
    for attr in parse_attrs(attrs)? {
        match attr {
            Attr::VerusMacro => vs.verus_macro = true,
            Attr::ExternalBody => vs.external_body = true,
            Attr::External => vs.external = true,
            Attr::Opaque => vs.opaque = true,
            Attr::Publish => vs.publish = true,
            Attr::OpaqueOutsideModule => vs.opaque_outside_module = true,
            Attr::MaybeNegative => vs.maybe_negative = true,
            Attr::StrictlyPositive => vs.strictly_positive = true,
            Attr::BroadcastForall => vs.broadcast_forall = true,
            Attr::NoAutoTrigger => vs.no_auto_trigger = true,
            Attr::Autoview => vs.autoview = true,
            Attr::CustomReqErr(s) => vs.custom_req_err_main = Some(s.clone()),
            Attr::CustomReqErrIdx(s, i) => vs.custom_req_err_idxs.push((s.clone(), i)),
            Attr::BitVector => vs.bit_vector = true,
            Attr::Unforgeable => vs.unforgeable = true,
            Attr::Atomic => vs.atomic = true,
            Attr::IntegerRing => vs.integer_ring = true,
            Attr::IsVariant(variant_ident) => vs.is_variant = Some(variant_ident),
            Attr::GetVariant(variant_ident, field_ident) => {
                vs.get_variant = Some((variant_ident, field_ident))
            }
            Attr::DecreasesBy => vs.decreases_by = true,
            Attr::CheckRecommends => vs.check_recommends = true,
            Attr::NonLinear => vs.nonlinear = true,
            Attr::SpinoffProver => vs.spinoff_prover = true,
            _ => {}
        }
    }
    Ok(vs)
}
