//! Erasure consistency check (`-V check-erasure`, or `VERUS_CHECK_ERASURE=1`).
//!
//! Verus runs rustc twice: the verify run type-checks the Keep expansion of `verus!` (which Verus
//! turns into VIR and verifies), and the compile run type-checks and compiles the Erase expansion.
//! The two expansions are type-checked independently, so they can disagree on the type of an
//! expression, on the item a name resolves to, or on exec control flow.
//!
//! This module builds, in each run, a table keyed by source location (file, byte offsets) of:
//!   (a) the type of each expression and pattern binding,
//!   (b) the resolved target of each call, method call, path and struct expression,
//!   (c) exec control flow: break/continue/return targets, loops, ifs, match arms and the tests
//!       that their patterns perform.
//! In the verify run, ghost code (as determined by VIR mode checking) is projected out, except
//! for control flow that VIR models as exec (break/continue targeting an exec loop).
//! After the compile run, the two tables are compared and each difference is reported as an error.

use rustc_hir::def::{DefKind, Res};
use rustc_hir::intravisit::{self, Visitor};
use rustc_hir::{
    Body, BodyId, Expr, ExprKind, HirId, LetStmt, Node, Pat, PatExpr, PatExprKind, PatKind, QPath,
};
use rustc_middle::ty::{self, GenericArgsRef, Ty, TyCtxt, TypeckResults};
use rustc_span::def_id::{DefId, LocalDefId};
use rustc_span::{Span, source_map::SourceMap};
use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};

/// Source location of a node, independent of the rustc session.
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct Loc {
    pub file: String,
    pub lo: u32,
    pub hi: u32,
    /// For a token produced by `macro_rules!` expansions: the chain of macro call sites
    /// (outermost last); empty for a token written in the source at this location.
    pub via: String,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum FactKind {
    /// (a) type of an expression
    Type,
    /// (a) type of an expression after adjustments (autoref, deref, unsizing)
    AdjType,
    /// (a) type and binding mode of a pattern binding
    Binding,
    /// (b) resolved target of a path, call, method call, overloaded operator or struct expression
    Res,
    /// (c) control flow: break/continue/return target, loop/if structure
    Flow,
    /// (c) the tests a pattern performs (match arms, let-else, if-let)
    Shape,
}

impl FactKind {
    fn describe(&self) -> &'static str {
        match self {
            FactKind::Type => "type",
            FactKind::AdjType => "adjusted type",
            FactKind::Binding => "binding",
            FactKind::Res => "resolves to",
            FactKind::Flow => "control flow",
            FactKind::Shape => "pattern tests",
        }
    }
}

#[derive(Clone, Debug)]
pub struct Fact {
    pub kind: FactKind,
    /// String compared between the two runs
    pub cmp: String,
    /// String shown to the user
    pub show: String,
    /// Verify run only: alternative comparison string under projection S3 (ghost outputs)
    pub alt: Option<String>,
    /// If true, this fact is reported even when the other run has no node at this location
    /// (control flow written by the user: the node's text starts with its keyword)
    pub one_sided: bool,
}

pub struct FactVal {
    pub cmp: String,
    pub show: String,
    pub alt: Option<String>,
}

#[derive(Clone, Debug, Default)]
pub struct BodyTable {
    pub owner: String,
    pub body: Option<Loc>,
    /// Alignment key: the body's location, plus the owner's path when the body comes from a
    /// macro expansion (bodies generated by one `macro_rules!` share a location).
    pub key: (Loc, String),
    /// key: (location, node class)
    pub nodes: BTreeMap<(Loc, &'static str), Vec<Fact>>,
}

#[derive(Clone, Debug, Default)]
pub struct Table {
    pub bodies: Vec<BodyTable>,
}

/// Verify-run projection: which HIR nodes are exec code according to VIR mode checking.
#[derive(Default)]
pub struct ExecInfo {
    pub hir_exec: HashMap<HirId, bool>,
    pub pat_exec: HashMap<HirId, bool>,
    pub erased_trees: HashSet<HirId>,
    /// does the expression have mode exec (used for if conditions and match scrutinees)
    pub hir_mode_exec: HashMap<HirId, bool>,
}

impl ExecInfo {
    pub fn new(
        hir_vir: &[(HirId, vir::messages::AstId)],
        expr_exec: &[(vir::messages::AstId, bool)],
        pat_modes: &[(vir::messages::AstId, vir::ast::Mode)],
        expr_modes: &[(vir::messages::AstId, vir::ast::Mode)],
        resolved_calls: &[(HirId, rustc_span::SpanData, crate::erase::ResolvedCall, bool)],
    ) -> Self {
        let mut ast_exec: HashMap<vir::messages::AstId, bool> = HashMap::new();
        for (id, exec) in expr_exec {
            let e = ast_exec.entry(*id).or_insert(false);
            *e = *e || *exec;
        }
        // result mode of each expression: exec if any VIR node built from it has mode exec
        let mut ast_mode: HashMap<vir::messages::AstId, bool> = HashMap::new();
        for (id, mode) in expr_modes {
            let e = ast_mode.entry(*id).or_insert(false);
            *e = *e || *mode == vir::ast::Mode::Exec;
        }
        let mut ast_pat: HashMap<vir::messages::AstId, bool> = HashMap::new();
        for (id, mode) in pat_modes {
            let e = ast_pat.entry(*id).or_insert(false);
            *e = *e || *mode == vir::ast::Mode::Exec;
        }
        let mut info = ExecInfo::default();
        // Calls that erasure removes as a whole tree (spec directives such as requires/ensures,
        // loop invariants, decreases): not exec, whatever their position.
        for (hir_id, _, resolved_call, _) in resolved_calls {
            if matches!(
                resolved_call,
                crate::erase::ResolvedCall::SpecPure
                    | crate::erase::ResolvedCall::MiscEraseAbsolutely
                    | crate::erase::ResolvedCall::LoopSpec(..)
            ) {
                info.erased_trees.insert(*hir_id);
            }
        }
        for (hir_id, ast_id) in hir_vir {
            if let Some(exec) = ast_exec.get(ast_id) {
                // exec code: checked in an exec context and has mode exec
                let exec = *exec && *ast_mode.get(ast_id).unwrap_or(&true);
                let e = info.hir_exec.entry(*hir_id).or_insert(false);
                *e = *e || exec;
            }
            if let Some(m) = ast_mode.get(ast_id) {
                let e = info.hir_mode_exec.entry(*hir_id).or_insert(false);
                *e = *e || *m;
            }
            if let Some(exec) = ast_pat.get(ast_id) {
                let e = info.pat_exec.entry(*hir_id).or_insert(false);
                *e = *e || *exec;
            }
        }
        info
    }
}

/// Print with the defining paths of items: no trimmed paths (so that two items with the same
/// short name differ) and no visible re-export paths (rustc may pick a different re-export in
/// each session).
fn no_paths<R>(f: impl FnOnce() -> R) -> R {
    ty::print::with_no_visible_paths!(ty::print::with_no_trimmed_paths!(f()))
}

/// Closure types print with their source span, which `#[verus_spec]` on a
/// closure changes between the two runs; the closure's identity is the location of its node,
/// so the type prints without it.
fn strip_closure_locations(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(i) = rest.find('{') {
        out.push_str(&rest[..i]);
        let tail = &rest[i..];
        match (tail.starts_with("{closure@"), tail.find('}')) {
            (true, Some(j)) => {
                out.push_str("{closure}");
                rest = &tail[j + 1..];
            }
            _ => {
                out.push('{');
                rest = &tail[1..];
            }
        }
    }
    out.push_str(rest);
    out
}

pub fn loc_of(sm: &SourceMap, span: Span) -> Option<Loc> {
    let data = span.data();
    if data.lo.0 == 0 && data.hi.0 == 0 {
        return None;
    }
    let lo = sm.lookup_byte_offset(data.lo);
    let hi = sm.lookup_byte_offset(data.hi);
    if !std::sync::Arc::ptr_eq(&lo.sf, &hi.sf) {
        return None;
    }
    Some(Loc {
        file: lo.sf.name.prefer_local_unconditionally().to_string(),
        lo: lo.pos.0,
        hi: hi.pos.0,
        via: String::new(),
    })
}

fn loc_to_string(sm: &SourceMap, tcx_loc: &Loc) -> String {
    for sf in sm.files().iter() {
        if sf.name.prefer_local_unconditionally().to_string() == tcx_loc.file {
            let pos = sf.start_pos + rustc_span::BytePos(tcx_loc.lo);
            let l = sf.lookup_file_pos_with_col_display(pos);
            return format!("{}:{}:{}", tcx_loc.file, l.0, l.2 + 1);
        }
    }
    format!("{}@{}", tcx_loc.file, tcx_loc.lo)
}

fn span_of_loc(sm: &SourceMap, loc: &Loc) -> Option<Span> {
    for sf in sm.files().iter() {
        if sf.name.prefer_local_unconditionally().to_string() == loc.file {
            let lo = sf.start_pos + rustc_span::BytePos(loc.lo);
            let hi = sf.start_pos + rustc_span::BytePos(loc.hi);
            return Some(Span::with_root_ctxt(lo, hi));
        }
    }
    None
}

struct Walker<'a, 'tcx> {
    tcx: TyCtxt<'tcx>,
    sm: &'a SourceMap,
    typeck: Vec<&'tcx TypeckResults<'tcx>>,
    typing_env: ty::TypingEnv<'tcx>,
    exec_info: Option<&'a ExecInfo>,
    /// is the current node exec code (always true in the compile run)
    exec: bool,
    /// enclosing bodies (fn or closure): location and exec-ness, for `return` targets
    body_stack: Vec<(Option<Loc>, bool)>,
    /// exec-ness computed for each loop node (target of break/continue)
    loop_exec: HashMap<HirId, bool>,
    table: BodyTable,
}

impl<'a, 'tcx> Walker<'a, 'tcx> {
    fn typeck(&self) -> &'tcx TypeckResults<'tcx> {
        self.typeck.last().unwrap()
    }

    fn loc(&self, span: Span) -> Option<Loc> {
        loc_of(self.sm, span)
    }

    /// Rule 1 of user-token detection: the span must have the root syntax context.
    /// This excludes tokens created by `quote!`/`call_site`/`mixed_site`, `macro_rules!` bodies
    /// and rustc's own desugarings.
    ///
    /// Extension: a token produced by a `macro_rules!` (or other non-Verus bang macro) expansion
    /// is kept, with the chain of its macro call sites added to its location. Both runs expand
    /// the same macro at the same call site, so the chain identifies the same token in both.
    /// Tokens of Verus's own proc macros (`verus!`, `verus_spec`, ...) and rustc desugarings
    /// are excluded.
    fn user_loc(&self, span: Span) -> Option<Loc> {
        if span.is_dummy() {
            return None;
        }
        let mut chain: Vec<String> = vec![];
        let mut cur = span;
        while cur.from_expansion() {
            let data = cur.ctxt().outer_expn_data();
            match data.kind {
                rustc_span::hygiene::ExpnKind::Macro(
                    rustc_span::hygiene::MacroKind::Bang,
                    name,
                ) => {
                    let def = data.macro_def_id?;
                    let krate = self.tcx.crate_name(def.krate);
                    if krate.as_str().starts_with("verus_") {
                        return None;
                    }
                    let call = self.loc(data.call_site)?;
                    chain.push(format!("{name}!@{}:{}-{}", call.file, call.lo, call.hi));
                    cur = data.call_site;
                }
                _ => return None,
            }
        }
        let mut loc = self.loc(span)?;
        loc.via = chain.join(" > ");
        Some(loc)
    }

    /// Rule 2 (used for facts reported one-sidedly): the source text at the span starts
    /// with the expected keyword.
    fn starts_with_keyword(&self, span: Span, kw: &str) -> bool {
        match self.sm.span_to_snippet(span) {
            Ok(s) => {
                let s = s.trim_start();
                // allow a loop label before `loop`
                let s = if s.starts_with('\'') {
                    match s.find(':') {
                        Some(i) => s[i + 1..].trim_start(),
                        None => s,
                    }
                } else {
                    s
                };
                s.starts_with(kw)
                    && !s[kw.len()..].starts_with(|c: char| c.is_alphanumeric() || c == '_')
            }
            Err(_) => false,
        }
    }

    /// Type fact: a function item type is printed as the function it names (via `def_fact`),
    /// so that it follows the same projection as the resolved target.
    fn ty_fact(&self, ty: Ty<'tcx>) -> FactVal {
        if let ty::FnDef(def_id, args) = ty.kind() {
            let (cmp, show) = self.def_fact(*def_id, Some(args));
            return FactVal {
                cmp: format!("fn item {cmp}"),
                show: format!("fn item {show}"),
                alt: None,
            };
        }
        let show = self.ty_str(ty);
        let mut cmp = self.ty_str(self.erase_wrapper_args(ty));
        // S4: the receiver of a closure call is auto-referenced as `&` or `&mut` according to
        // the call trait (see def_fact)
        if let ty::Ref(_, inner, _) = ty.kind() {
            if let ty::Closure(..) = inner.kind() {
                cmp = format!("closure call receiver {}", self.ty_str(*inner));
            }
        }
        // S3 (verify run): a function with `with` ghost outputs returns `(T, Ghost<..>, ...)`
        // in the verified program and `T` in the compiled program.
        let alt = match ty.kind() {
            ty::Tuple(elems)
                if self.exec_info.is_some()
                    && elems.len() >= 2
                    && elems.iter().skip(1).all(|t| self.is_ghost_wrapper(t)) =>
            {
                Some(self.ty_str(self.erase_wrapper_args(elems[0])))
            }
            _ => None,
        };
        FactVal { cmp, show, alt }
    }

    fn is_ghost_wrapper(&self, ty: Ty<'tcx>) -> bool {
        self.wrapper_kind(ty).is_some()
    }

    /// S2: `Ghost<T>` and `Tracked<T>` are zero-sized in the compiled program; their argument has
    /// no run-time representation. In type facts (a), the argument is replaced by `()`.
    /// Resolved targets (b) keep the argument, so trait dispatch on `T` is still compared.
    fn erase_wrapper_args(&self, ty: Ty<'tcx>) -> Ty<'tcx> {
        use rustc_middle::ty::TypeFoldable;
        let tcx = self.tcx;
        let mut folder = ty::BottomUpFolder {
            tcx,
            ty_op: |t: Ty<'tcx>| match t.kind() {
                ty::Adt(adt, args) if self.is_ghost_wrapper(t) && args.len() == 1 => {
                    Ty::new_adt(tcx, *adt, tcx.mk_args(&[tcx.types.unit.into()]))
                }
                _ => t,
            },
            lt_op: |r| r,
            ct_op: |c| c,
        };
        ty.fold_with(&mut folder)
    }

    fn ty_str(&self, ty: Ty<'tcx>) -> String {
        strip_closure_locations(&self.ty_str_raw(ty))
    }

    fn ty_str_raw(&self, ty: Ty<'tcx>) -> String {
        let tcx = self.tcx;
        let ty = match tcx.try_normalize_erasing_regions(self.typing_env, ty::Unnormalized::new(ty))
        {
            Ok(ty) => ty,
            Err(_) => tcx.erase_and_anonymize_regions(ty),
        };
        let ty = tcx.erase_and_anonymize_regions(ty);
        no_paths(|| format!("{}", ty))
    }

    fn args_str(&self, args: Option<GenericArgsRef<'tcx>>) -> String {
        match args {
            None => String::new(),
            Some(args) if args.is_empty() => String::new(),
            Some(args) => {
                let tcx = self.tcx;
                let args = match tcx
                    .try_normalize_erasing_regions(self.typing_env, ty::Unnormalized::new(args))
                {
                    Ok(a) => a,
                    Err(_) => tcx.erase_and_anonymize_regions(args),
                };
                let args = tcx.erase_and_anonymize_regions(args);
                let v: Vec<String> = args
                    .iter()
                    .filter(|a| !matches!(a.kind(), ty::GenericArgKind::Lifetime(_)))
                    .map(|a| strip_closure_locations(&no_paths(|| format!("{}", a))))
                    .collect();
                format!("::<{}>", v.join(", "))
            }
        }
    }

    /// Projection of the calls that `verus!` emits for `Ghost(e)` / `Tracked(e)`:
    /// the verify run calls `verus_builtin::ghost_exec::<T>(e)` / `tracked_exec::<T>(e)`,
    /// the compile run calls `Ghost::<T>::assume_new_fallback(|| unreachable!())` /
    /// `Tracked::<T>::assume_new_fallback(..)` (with verus_builtin's `Ghost`/`Tracked`).
    /// Both print as `erased-wrapper Ghost<T>`.
    fn erasure_boundary(
        &self,
        def_id: DefId,
        args: Option<GenericArgsRef<'tcx>>,
    ) -> Option<String> {
        let tcx = self.tcx;
        let first_ty = || -> String {
            match args {
                Some(args) if args.len() > 0 => match args[0].kind() {
                    ty::GenericArgKind::Type(t) => self.ty_str(t),
                    _ => String::new(),
                },
                _ => String::new(),
            }
        };
        // Verus's own items are identified by their diagnostic item names (as verus_items.rs
        // does), not by crate name: with --is-core, verus_builtin is a module of the crate.
        if let Some(d) = tcx.get_diagnostic_name(def_id) {
            return match d.as_str() {
                "verus::verus_builtin::ghost_exec" => {
                    Some(format!("erased-wrapper Ghost<{}>", first_ty()))
                }
                "verus::verus_builtin::tracked_exec" => {
                    Some(format!("erased-wrapper Tracked<{}>", first_ty()))
                }
                _ => None,
            };
        }
        if tcx.opt_item_name(def_id).map_or(true, |n| n.as_str() != "assume_new_fallback") {
            return None;
        }
        let parent = tcx.parent(def_id);
        if !matches!(tcx.def_kind(parent), DefKind::Impl { of_trait: false }) {
            return None;
        }
        let self_ty = tcx.type_of(parent).skip_binder();
        match self.wrapper_kind(self_ty) {
            Some(w) => Some(format!("erased-wrapper {w}<{}>", first_ty())),
            None => None,
        }
    }

    /// `Some("Ghost")` / `Some("Tracked")` for verus_builtin's `Ghost<T>` / `Tracked<T>`
    fn wrapper_kind(&self, ty: Ty<'tcx>) -> Option<&'static str> {
        let ty::Adt(adt, _) = ty.kind() else { return None };
        match self.tcx.get_diagnostic_name(adt.did())?.as_str() {
            "verus::verus_builtin::Ghost" => Some("Ghost"),
            "verus::verus_builtin::Tracked" => Some("Tracked"),
            _ => None,
        }
    }

    /// Print a resolved definition.
    /// Local definitions are compared by kind and the location of their name token, so that
    /// a generated item whose name token is the user's token (e.g. the verified twin
    /// `_VERUS_VERIFIED_f` of `f`) compares equal to the user's item.
    fn def_fact(&self, def_id: DefId, args: Option<GenericArgsRef<'tcx>>) -> (String, String) {
        let tcx = self.tcx;
        if let Some(s) = self.erasure_boundary(def_id, args) {
            // S2: the wrapper's argument is not compared (see erase_wrapper_args)
            let cmp = s.split('<').next().unwrap_or(&s).to_string();
            return (cmp, s);
        }
        // S4: a call of a closure through `Fn::call`, `FnMut::call_mut` or `FnOnce::call_once`.
        // VIR models a closure call as CallLambda, whatever the trait; rustc picks the trait from
        // the closure kind it infers from the body's uses of captures, and the verified body
        // contains ghost uses that the compiled body lacks. The callee is the closure itself.
        if let Some(tr) = tcx.trait_of_assoc(def_id) {
            if tcx.fn_trait_kind_from_def_id(tr).is_some() {
                if let Some(args) = args {
                    if let Some(ty::GenericArgKind::Type(t)) = args.get(0).map(|a| a.kind()) {
                        if let ty::Closure(..) = t.kind() {
                            let path = no_paths(|| tcx.def_path_str(def_id));
                            let show = format!("{path}{}", self.args_str(Some(args)));
                            let cmp = format!(
                                "closure call {}{}",
                                self.ty_str(t),
                                self.args_str(Some(tcx.mk_args(&args[1..])))
                            );
                            return (cmp, show);
                        }
                    }
                }
            }
        }
        let args_s = self.args_str(args);
        let path = no_paths(|| tcx.def_path_str(def_id));
        let show = format!("{path}{args_s}");
        if let Some(local) = def_id.as_local() {
            let span = tcx.def_ident_span(local).unwrap_or_else(|| tcx.def_span(local));
            let kind = tcx.def_kind(def_id);
            let cmp = match self.loc(span) {
                Some(loc) => format!("{kind:?} @{}:{}-{}{args_s}", loc.file, loc.lo, loc.hi),
                None => format!("{kind:?} {show}"),
            };
            let at = self.loc(span).map(|l| loc_to_string(self.sm, &l)).unwrap_or_default();
            (cmp, format!("{show} (defined at {at})"))
        } else {
            (show.clone(), show)
        }
    }

    fn local_fact(&self, hir_id: HirId) -> (String, String) {
        let span = match self.tcx.hir_node(hir_id) {
            Node::Pat(Pat { kind: PatKind::Binding(_, _, ident, _), .. }) => ident.span,
            _ => self.tcx.hir_span(hir_id),
        };
        let cmp = match self.loc(span) {
            Some(loc) => format!("local @{}:{}-{}", loc.file, loc.lo, loc.hi),
            None => "local <no location>".to_string(),
        };
        (cmp, format!("local variable bound at {}", self.sm.span_to_diagnostic_string(span)))
    }

    fn res_fact(&self, res: Res, hir_id: HirId) -> Option<(String, String)> {
        match res {
            Res::Local(id) => Some(self.local_fact(id)),
            Res::Def(_, def_id) => Some(self.def_fact(def_id, self.typeck().node_args_opt(hir_id))),
            Res::SelfCtor(def_id) => {
                Some(self.def_fact(def_id, self.typeck().node_args_opt(hir_id)))
            }
            _ => None,
        }
    }

    fn push(&mut self, loc: Loc, class: &'static str, kind: FactKind, fact: (String, String)) {
        self.push_one_sided(loc, class, kind, fact, false);
    }

    fn push_one_sided(
        &mut self,
        loc: Loc,
        class: &'static str,
        kind: FactKind,
        fact: (String, String),
        one_sided: bool,
    ) {
        let (cmp, show) = fact;
        let f = Fact { kind, cmp, show, one_sided, alt: None };
        self.table.nodes.entry((loc, class)).or_default().push(f);
    }

    fn push_val(&mut self, loc: Loc, class: &'static str, kind: FactKind, v: FactVal) {
        self.table.nodes.entry((loc, class)).or_default().push(Fact {
            kind,
            cmp: v.cmp,
            show: v.show,
            one_sided: false,
            alt: v.alt,
        });
    }

    fn sub_pat_exec(&self, pat: &Pat<'tcx>, parent_exec: bool) -> bool {
        match self.exec_info {
            None => true,
            Some(info) => *info.pat_exec.get(&pat.hir_id).unwrap_or(&parent_exec),
        }
    }

    fn pat_expr_str(&self, e: &PatExpr<'tcx>) -> String {
        match &e.kind {
            PatExprKind::Lit { lit, negated } => {
                format!("{}{:?}", if *negated { "-" } else { "" }, lit.node)
            }
            PatExprKind::Path(qpath) => {
                let res = self.typeck().qpath_res(qpath, e.hir_id);
                match self.res_fact(res, e.hir_id) {
                    Some((cmp, _)) => format!("const {cmp}"),
                    None => format!("path {res:?}"),
                }
            }
        }
    }

    fn variant_name(&self, pat: &Pat<'tcx>, qpath: &QPath<'tcx>) -> (String, bool) {
        // returns (printed variant, does matching it perform a test?)
        let ty = self.typeck().node_type_opt(pat.hir_id);
        let is_test = match ty.map(|t| t.kind()) {
            Some(ty::Adt(adt, _)) => adt.is_enum() && adt.variants().len() > 1,
            _ => false,
        };
        let res = self.typeck().qpath_res(qpath, pat.hir_id);
        let name = match res {
            Res::Def(_, def_id) | Res::SelfCtor(def_id) => self.def_fact(def_id, None).0,
            _ => format!("{res:?}"),
        };
        (name, is_test)
    }

    /// Print the tests that a pattern performs at run time. Bindings and wildcards print as `_`.
    /// In the verify run, a sub-pattern that VIR mode checking gives a non-exec mode prints as
    /// `ghost(..)` when it performs a test (and as `_` otherwise).
    /// Returns (shape, performs a test?).
    fn shape(&self, pat: &Pat<'tcx>, parent_exec: bool) -> (String, bool) {
        let exec = self.sub_pat_exec(pat, parent_exec);
        let (s, test) = self.shape_inner(pat, exec);
        if !test {
            ("_".to_string(), false)
        } else if !exec && parent_exec {
            (format!("ghost({s})"), true)
        } else {
            (s, true)
        }
    }

    fn shapes(&self, pats: &[Pat<'tcx>], exec: bool) -> (Vec<String>, bool) {
        let mut v = vec![];
        let mut test = false;
        for p in pats {
            let (s, t) = self.shape(p, exec);
            test = test || t;
            v.push(s);
        }
        (v, test)
    }

    fn shape_inner(&self, pat: &Pat<'tcx>, exec: bool) -> (String, bool) {
        match &pat.kind {
            PatKind::Missing | PatKind::Wild | PatKind::Never | PatKind::Err(_) => {
                ("_".to_string(), false)
            }
            PatKind::Binding(_, _, _, None) => ("_".to_string(), false),
            PatKind::Binding(_, _, _, Some(sub)) => self.shape(sub, exec),
            PatKind::Struct(qpath, fields, _) => {
                let (name, mut test) = self.variant_name(pat, qpath);
                let mut fs = vec![];
                for f in fields.iter() {
                    let (s, t) = self.shape(f.pat, exec);
                    test = test || t;
                    fs.push(format!("{}: {}", f.ident, s));
                }
                fs.sort();
                (format!("{name} {{ {} }}", fs.join(", ")), test)
            }
            PatKind::TupleStruct(qpath, pats, _) => {
                let (name, test0) = self.variant_name(pat, qpath);
                let (v, t) = self.shapes(pats, exec);
                (format!("{name}({})", v.join(", ")), test0 || t)
            }
            PatKind::Or(pats) => {
                let (v, _) = self.shapes(pats, exec);
                (format!("({})", v.join(" | ")), true)
            }
            PatKind::Tuple(pats, _) => {
                let (v, t) = self.shapes(pats, exec);
                (format!("({})", v.join(", ")), t)
            }
            PatKind::Box(p) => {
                let (s, t) = self.shape(p, exec);
                (format!("box {s}"), t)
            }
            PatKind::Deref(p) => {
                let (s, t) = self.shape(p, exec);
                (format!("deref {s}"), t)
            }
            PatKind::Ref(p, _, m) => {
                let (s, t) = self.shape(p, exec);
                (format!("&{}{s}", m.prefix_str()), t)
            }
            PatKind::Expr(e) => (self.pat_expr_str(e), true),
            PatKind::Guard(p, _) => {
                let (s, _) = self.shape(p, exec);
                (format!("{s} if .."), true)
            }
            PatKind::Range(lo, hi, end) => {
                let lo = lo.map(|e| self.pat_expr_str(e)).unwrap_or_default();
                let hi = hi.map(|e| self.pat_expr_str(e)).unwrap_or_default();
                (format!("{lo}{end}{hi}"), true)
            }
            PatKind::Slice(before, mid, after) => {
                let (b, _) = self.shapes(before, exec);
                let (a, _) = self.shapes(after, exec);
                let m = match mid {
                    Some(m) => format!(", {}.., ", self.shape(m, exec).0),
                    None => ", ".to_string(),
                };
                (format!("[{}{m}{}]", b.join(", "), a.join(", ")), true)
            }
        }
    }

    /// Verify run: if VIR mode checking gives the condition of an exec `if` (or the scrutinee
    /// of an exec `match`) a non-exec mode, the branch is decided by ghost data in the verified
    /// program; print that, so that it differs from the compiled program.
    fn non_exec_decider(&self, cond: &Expr<'tcx>) -> &'static str {
        let Some(info) = self.exec_info else { return "" };
        let mut c = cond;
        while let ExprKind::DropTemps(inner) = &c.kind {
            c = inner;
        }
        if let ExprKind::Let(_) = &c.kind {
            return ""; // `if let`: the pattern shape carries the modes
        }
        match info.hir_mode_exec.get(&c.hir_id) {
            Some(false) => " [decided by a non-exec value]",
            _ => "",
        }
    }

    fn record_flow_target(&mut self, e: &Expr<'tcx>, what: &'static str, kw: &str) {
        // break/continue: record the target loop; included whenever the target loop is exec,
        // even if this node is ghost code (VIR treats it as exec control flow).
        let (ExprKind::Break(dest, _) | ExprKind::Continue(dest)) = &e.kind else { return };
        let Ok(target) = dest.target_id else { return };
        let target_exec = *self.loop_exec.get(&target).unwrap_or(&self.exec);
        if !(self.exec || target_exec) {
            return;
        }
        let Some(loc) = self.user_loc(e.span) else { return };
        let target_span = self.tcx.hir_span(target);
        let tloc = self.loc(target_span);
        let label = dest.label.map(|l| format!(" '{}", l.ident.name)).unwrap_or_default();
        let cmp = match &tloc {
            Some(t) => format!("{what}{label} -> loop @{}:{}-{}", t.file, t.lo, t.hi),
            None => format!("{what}{label} -> ?"),
        };
        let show = format!(
            "`{what}{label}` exiting the loop at {}",
            self.sm.span_to_diagnostic_string(target_span)
        );
        let one_sided = self.starts_with_keyword(e.span, kw);
        self.push_one_sided(loc, what, FactKind::Flow, (cmp, show), one_sided);
    }

    fn record_expr(&mut self, e: &'tcx Expr<'tcx>) {
        match &e.kind {
            ExprKind::Break(..) => self.record_flow_target(e, "break", "break"),
            ExprKind::Continue(..) => self.record_flow_target(e, "continue", "continue"),
            ExprKind::Ret(_) => {
                let (bloc, bexec) = self.body_stack.last().cloned().unwrap_or((None, true));
                if self.exec || bexec {
                    if let Some(loc) = self.user_loc(e.span) {
                        let cmp = match &bloc {
                            Some(b) => format!("return -> body @{}:{}-{}", b.file, b.lo, b.hi),
                            None => "return -> ?".to_string(),
                        };
                        let show = "`return` from the enclosing function".to_string();
                        let one_sided = self.starts_with_keyword(e.span, "return");
                        self.push_one_sided(loc, "return", FactKind::Flow, (cmp, show), one_sided);
                    }
                }
            }
            _ => {}
        }
        if !self.exec {
            return;
        }
        let Some(loc) = self.user_loc(e.span) else { return };
        let class = expr_class(e);
        let typeck = self.typeck();
        // (a)
        if let Some(ty) = typeck.expr_ty_opt(e) {
            let t = self.ty_fact(ty);
            self.push_val(loc.clone(), class, FactKind::Type, t);
            if let Some(aty) = typeck.expr_ty_adjusted_opt(e) {
                if aty != ty {
                    let a = self.ty_fact(aty);
                    self.push_val(loc.clone(), class, FactKind::AdjType, a);
                }
            }
        }
        // (b)
        if let Some((_, def_id)) = typeck.type_dependent_def(e.hir_id) {
            let f = self.def_fact(def_id, typeck.node_args_opt(e.hir_id));
            self.push(loc.clone(), class, FactKind::Res, f);
        }
        match &e.kind {
            ExprKind::Path(qpath) => {
                let res = typeck.qpath_res(qpath, e.hir_id);
                if let Some(f) = self.res_fact(res, e.hir_id) {
                    self.push(loc.clone(), class, FactKind::Res, f);
                }
            }
            ExprKind::Struct(qpath, _, _) => {
                let res = typeck.qpath_res(qpath, e.hir_id);
                if let Some(f) = self.res_fact(res, e.hir_id) {
                    self.push(loc.clone(), class, FactKind::Res, f);
                }
            }
            ExprKind::Call(callee, _) => {
                if let Some(cty) = typeck.node_type_opt(callee.hir_id) {
                    if let ty::FnDef(def_id, args) = cty.kind() {
                        let f = self.def_fact(*def_id, Some(args));
                        self.push(loc.clone(), class, FactKind::Res, f);
                    }
                }
            }
            _ => {}
        }
        // (c)
        match &e.kind {
            ExprKind::Loop(_, label, source, _) => {
                let label = label.map(|l| format!(" '{}", l.ident.name)).unwrap_or_default();
                let s = format!("loop{label} ({source:?})");
                self.push(loc.clone(), class, FactKind::Flow, (s.clone(), s));
            }
            ExprKind::If(cond, _, els) => {
                let s = format!(
                    "if{}{}",
                    self.non_exec_decider(cond),
                    if els.is_some() { " else" } else { "" }
                );
                self.push(loc.clone(), class, FactKind::Flow, (s.clone(), s));
            }
            ExprKind::Match(scrutinee, arms, source) => {
                let decider = self.non_exec_decider(scrutinee);
                let mut v = vec![];
                for arm in arms.iter() {
                    let (s, _) = self.shape(arm.pat, true);
                    let g = if arm.guard.is_some() { " if <guard>" } else { "" };
                    v.push(format!("{s}{g}"));
                }
                let source = match source {
                    rustc_hir::MatchSource::TryDesugar(_) => "TryDesugar".to_string(),
                    _ => format!("{source:?}"),
                };
                let s = format!("match ({source}){decider} {{ {} }}", v.join("; "));
                self.push(loc.clone(), class, FactKind::Shape, (s.clone(), s));
            }
            ExprKind::Let(let_expr) => {
                let (s, _) = self.shape(let_expr.pat, true);
                let s = format!("let {s}");
                self.push(loc.clone(), class, FactKind::Shape, (s.clone(), s));
            }
            _ => {}
        }
    }

    fn record_pat(&mut self, p: &'tcx Pat<'tcx>) {
        if !self.exec {
            return;
        }
        if let PatKind::Binding(_, _, ident, _) = &p.kind {
            let Some(loc) = self.user_loc(ident.span) else { return };
            let typeck = self.typeck();
            if let Some(ty) = typeck.node_type_opt(p.hir_id) {
                let bm = typeck.pat_binding_modes().get(p.hir_id).copied();
                let bm = match bm {
                    Some(bm) => format!("{:?} ", bm),
                    None => String::new(),
                };
                let show = format!("{bm}{}: {}", ident.name, self.ty_str(ty));
                let cmp =
                    format!("{bm}{}: {}", ident.name, self.ty_str(self.erase_wrapper_args(ty)));
                let v = FactVal { cmp, show, alt: None };
                self.push_val(loc, "pat-binding", FactKind::Binding, v);
            }
        }
    }
}

fn expr_class(e: &Expr<'_>) -> &'static str {
    match &e.kind {
        ExprKind::ConstBlock(..) => "ConstBlock",
        ExprKind::Array(..) => "Array",
        ExprKind::Call(..) => "Call",
        ExprKind::MethodCall(..) => "MethodCall",
        ExprKind::Use(..) => "Use",
        ExprKind::Tup(..) => "Tup",
        ExprKind::Binary(..) => "Binary",
        ExprKind::Unary(..) => "Unary",
        ExprKind::Lit(..) => "Lit",
        ExprKind::Cast(..) => "Cast",
        ExprKind::Type(..) => "Type",
        ExprKind::DropTemps(..) => "DropTemps",
        ExprKind::Let(..) => "Let",
        ExprKind::If(..) => "If",
        ExprKind::Loop(..) => "Loop",
        ExprKind::Match(..) => "Match",
        ExprKind::Closure(..) => "Closure",
        ExprKind::Block(..) => "Block",
        ExprKind::Assign(..) => "Assign",
        ExprKind::AssignOp(..) => "AssignOp",
        ExprKind::Field(..) => "Field",
        ExprKind::Index(..) => "Index",
        ExprKind::Path(..) => "Path",
        ExprKind::AddrOf(..) => "AddrOf",
        ExprKind::Break(..) => "break",
        ExprKind::Continue(..) => "continue",
        ExprKind::Ret(..) => "return",
        ExprKind::Become(..) => "Become",
        ExprKind::InlineAsm(..) => "InlineAsm",
        ExprKind::OffsetOf(..) => "OffsetOf",
        ExprKind::Struct(..) => "Struct",
        ExprKind::Repeat(..) => "Repeat",
        ExprKind::Yield(..) => "Yield",
        ExprKind::UnsafeBinderCast(..) => "UnsafeBinderCast",
        ExprKind::Err(..) => "Err",
    }
}

impl<'a, 'tcx> Visitor<'tcx> for Walker<'a, 'tcx> {
    type NestedFilter = rustc_middle::hir::nested_filter::OnlyBodies;

    fn maybe_tcx(&mut self) -> TyCtxt<'tcx> {
        self.tcx
    }

    fn visit_nested_body(&mut self, id: BodyId) {
        let owner = self.tcx.hir_body_owner_def_id(id);
        let typeck = self.tcx.typeck(owner);
        self.typeck.push(typeck);
        let body = self.tcx.hir_body(id);
        self.visit_body(body);
        self.typeck.pop();
    }

    fn visit_expr(&mut self, e: &'tcx Expr<'tcx>) {
        let saved = self.exec;
        if let Some(info) = self.exec_info {
            if let Some(x) = info.hir_exec.get(&e.hir_id) {
                self.exec = *x;
            }
            if info.erased_trees.contains(&e.hir_id) {
                self.exec = false;
            }
        }
        if let ExprKind::Loop(..) = &e.kind {
            self.loop_exec.insert(e.hir_id, self.exec);
        }
        self.record_expr(e);
        if let ExprKind::Closure(_) = &e.kind {
            let loc = self.loc(e.span);
            self.body_stack.push((loc, self.exec));
            intravisit::walk_expr(self, e);
            self.body_stack.pop();
        } else {
            intravisit::walk_expr(self, e);
        }
        self.exec = saved;
    }

    fn visit_pat(&mut self, p: &'tcx Pat<'tcx>) {
        let saved = self.exec;
        if let Some(info) = self.exec_info {
            if let Some(x) = info.pat_exec.get(&p.hir_id) {
                self.exec = *x;
            }
        }
        self.record_pat(p);
        intravisit::walk_pat(self, p);
        self.exec = saved;
    }

    fn visit_local(&mut self, l: &'tcx LetStmt<'tcx>) {
        if self.exec {
            let pat_exec = self.sub_pat_exec(l.pat, true);
            if pat_exec {
                if let Some(loc) = self.user_loc(l.span) {
                    let (s, _) = self.shape(l.pat, true);
                    let s = format!("let {s}{}", if l.els.is_some() { " else" } else { "" });
                    self.push(loc, "let-stmt", FactKind::Shape, (s.clone(), s));
                }
            }
        }
        intravisit::walk_local(self, l);
    }
}

/// Build the table for one body owner (and its closures).
fn build_body_table<'tcx>(
    tcx: TyCtxt<'tcx>,
    def_id: LocalDefId,
    exec_info: Option<&ExecInfo>,
) -> Option<BodyTable> {
    let body: &'tcx Body<'tcx> = tcx.hir_maybe_body_owned_by(def_id)?;
    let typeck = tcx.typeck(def_id);
    if typeck.tainted_by_errors.is_some() {
        return None;
    }
    let sm = tcx.sess.source_map();
    if !is_user_body(tcx, def_id, body) {
        return None;
    }
    let body_loc = loc_of(sm, body.value.span)?;
    let key = body_key(tcx, def_id, body, body_loc.clone());
    let mut w = Walker {
        tcx,
        sm,
        typeck: vec![typeck],
        typing_env: ty::TypingEnv::non_body_analysis(tcx, def_id),
        exec_info,
        exec: true,
        body_stack: vec![(Some(body_loc.clone()), true)],
        loop_exec: HashMap::new(),
        table: BodyTable {
            owner: no_paths(|| tcx.def_path_str(def_id.to_def_id())),
            body: Some(body_loc),
            key,
            nodes: BTreeMap::new(),
        },
    };
    w.visit_body(body);
    Some(w.table)
}

/// Verify run: build the table for every exec body owner whose body Verus verifies.
pub fn build_verify_table<'tcx>(
    tcx: TyCtxt<'tcx>,
    bodies: &[(LocalDefId, vir::ast::Mode, bool)],
    exec_info: &ExecInfo,
) -> Table {
    let mut table = Table::default();
    let mut seen = HashSet::new();
    for (def_id, mode, has_body) in bodies {
        if *mode != vir::ast::Mode::Exec || !*has_body || !seen.insert(*def_id) {
            continue;
        }
        if tcx.is_typeck_child(def_id.to_def_id()) {
            continue;
        }
        if let Some(t) = build_body_table(tcx, *def_id, Some(exec_info)) {
            table.bodies.push(t);
        }
    }
    table
}

/// Rule 2 for bodies: the body of a function must be a block written in the source (its text
/// starts with `{`). A proc macro that emits a function with a body spanned by some other user
/// token (for example the `struct` item `exec_spec!` translates) produces a body that is not
/// the user's; such bodies are left out of both tables.
fn is_user_body<'tcx>(tcx: TyCtxt<'tcx>, def_id: LocalDefId, body: &Body<'tcx>) -> bool {
    match tcx.def_kind(def_id) {
        DefKind::Fn | DefKind::AssocFn => {
            match tcx.sess.source_map().span_to_snippet(body.value.span) {
                Ok(s) => s.trim_start().starts_with('{'),
                Err(_) => false,
            }
        }
        _ => true,
    }
}

fn body_key<'tcx>(
    tcx: TyCtxt<'tcx>,
    def_id: LocalDefId,
    body: &Body<'tcx>,
    loc: Loc,
) -> (Loc, String) {
    if body.value.span.from_expansion() {
        // identify the owner by its parent's path and its name, with the unerased-proxy prefix
        // removed as rust_to_vir_func::fixup_unerased_proxy_path does to name the VIR function
        let parent = tcx.parent(def_id.to_def_id());
        let parent = no_paths(|| tcx.def_path_str(parent));
        let name = tcx.opt_item_name(def_id.to_def_id()).map(|n| n.to_string()).unwrap_or_default();
        let name = name.strip_prefix("VERUS_UNERASED_PROXY__").unwrap_or(&name).to_string();
        (loc, format!("{parent}::{name}"))
    } else {
        (loc, String::new())
    }
}

/// Compile run: build the tables of the body owners whose body location matches a verified body.
pub fn build_compile_table<'tcx>(tcx: TyCtxt<'tcx>, verified: &Table) -> Table {
    let sm = tcx.sess.source_map();
    let wanted: HashSet<&(Loc, String)> = verified.bodies.iter().map(|b| &b.key).collect();
    let mut table = Table::default();
    for def_id in tcx.hir_body_owners() {
        if tcx.is_typeck_child(def_id.to_def_id()) {
            continue;
        }
        let Some(body) = tcx.hir_maybe_body_owned_by(def_id) else { continue };
        let Some(loc) = loc_of(sm, body.value.span) else { continue };
        let key = body_key(tcx, def_id, body, loc);
        if !wanted.contains(&key) {
            continue;
        }
        if let Some(t) = build_body_table(tcx, def_id, None) {
            table.bodies.push(t);
        }
    }
    table
}

pub struct Difference {
    pub loc: Loc,
    pub msg: String,
}

fn group(facts: &[Fact]) -> BTreeMap<FactKind, Vec<&Fact>> {
    let mut m: BTreeMap<FactKind, Vec<&Fact>> = BTreeMap::new();
    for f in facts {
        m.entry(f.kind).or_default().push(f);
    }
    for v in m.values_mut() {
        v.sort_by(|a, b| a.cmp.cmp(&b.cmp));
        v.dedup_by(|a, b| a.cmp == b.cmp);
    }
    m
}

fn show_list(v: &[&Fact]) -> String {
    let s: Vec<&str> = v.iter().map(|f| f.show.as_str()).collect();
    s.join(", ")
}

pub fn diff_tables(verified: &Table, compiled: &Table) -> Vec<Difference> {
    let mut diffs = vec![];
    // several compiled bodies may share a location (none expected); merge them
    let mut cmap: HashMap<&(Loc, String), Vec<&BodyTable>> = HashMap::new();
    for b in &compiled.bodies {
        cmap.entry(&b.key).or_default().push(b);
    }
    let mut done: BTreeSet<&(Loc, String)> = BTreeSet::new();
    for vb in &verified.bodies {
        let bkey = &vb.key;
        let bloc = &bkey.0;
        if !done.insert(bkey) {
            continue;
        }
        let Some(cbs) = cmap.get(bkey) else {
            diffs.push(Difference {
                loc: bloc.clone(),
                msg: format!(
                    "the body of `{}` is verified as exec code but the compiled program has no function with this body",
                    vb.owner
                ),
            });
            continue;
        };
        // S1: several compiled bodies with this location (the `#[verus_spec(with)]` pair `f` /
        // `_VERUS_VERIFIED_f`): drop the ones with no source-written expression other than the
        // body block itself (Erase replaces the verified twin's body by `unimplemented!()`).
        let cbs: Vec<&BodyTable> = if cbs.len() > 1 {
            cbs.iter()
                .copied()
                .filter(|b| {
                    b.nodes.keys().any(|(l, class)| {
                        l.via.is_empty() && *class != "pat-binding" && Some(l) != b.body.as_ref()
                    })
                })
                .collect()
        } else {
            cbs.clone()
        };
        // merge verified bodies with this location too
        let vbs: Vec<&BodyTable> = verified.bodies.iter().filter(|b| &b.key == bkey).collect();
        let mut vnodes: BTreeMap<&(Loc, &'static str), Vec<Fact>> = BTreeMap::new();
        for b in vbs {
            for (k, v) in &b.nodes {
                vnodes.entry(k).or_default().extend(v.iter().cloned());
            }
        }
        let mut cnodes: BTreeMap<&(Loc, &'static str), Vec<Fact>> = BTreeMap::new();
        for b in cbs {
            for (k, v) in &b.nodes {
                cnodes.entry(k).or_default().extend(v.iter().cloned());
            }
        }
        let keys: BTreeSet<&&(Loc, &'static str)> = vnodes.keys().chain(cnodes.keys()).collect();
        let empty = vec![];
        for key in keys {
            let vf = vnodes.get(*key).unwrap_or(&empty);
            let cf = cnodes.get(*key).unwrap_or(&empty);
            let vg = group(vf);
            let cg = group(cf);
            let kinds: BTreeSet<&FactKind> = vg.keys().chain(cg.keys()).collect();
            for kind in kinds {
                let vs = vg.get(kind);
                let cs = cg.get(kind);
                match (vs, cs) {
                    (Some(vs), Some(cs)) => {
                        let va: Vec<&String> = vs.iter().map(|f| &f.cmp).collect();
                        let ca: Vec<&String> = cs.iter().map(|f| &f.cmp).collect();
                        if va == ca {
                            continue;
                        }
                        // S3: a verified `(T, Ghost<..>, ..)` (ghost outputs) matches a compiled `T`
                        let mut va3: Vec<&String> = vs
                            .iter()
                            .map(|f| match &f.alt {
                                Some(a) if ca.contains(&a) && !ca.contains(&&f.cmp) => a,
                                _ => &f.cmp,
                            })
                            .collect();
                        va3.sort();
                        va3.dedup();
                        if va3 == ca {
                            continue;
                        }
                        // S5: a block that is `!` in the verified program and `()` in the compiled
                        // program: Keep appends ghost statements after the user's diverging tail
                        // (e.g. `open_invariant_end(..)` in open_local_invariant!), Erase does not.
                        // The diverging exec statement is itself compared.
                        if key.1 == "Block"
                            && matches!(kind, FactKind::Type)
                            && va.len() == 1
                            && va[0] == "!"
                            && ca.len() == 1
                            && ca[0] == "()"
                        {
                            continue;
                        }
                        diffs.push(Difference {
                            loc: key.0.clone(),
                            msg: format!(
                                "{} {} (compiled) vs {} (verified)",
                                kind.describe(),
                                show_list(cs),
                                show_list(vs)
                            ),
                        });
                    }
                    (Some(vs), None) => {
                        let rep: Vec<&Fact> = vs.iter().copied().filter(|f| f.one_sided).collect();
                        if rep.len() > 0 {
                            diffs.push(Difference {
                                loc: key.0.clone(),
                                msg: format!(
                                    "{} {} is exec control flow in the verified program, but the compiled program has no such node",
                                    kind.describe(),
                                    show_list(&rep)
                                ),
                            });
                        }
                    }
                    (None, _) => {}
                }
            }
        }
    }
    diffs
}

/// Compile run: build the compiled table, diff it against the verified table, report errors.
/// Returns the number of differences.
pub fn check_compile_run<'tcx>(tcx: TyCtxt<'tcx>, verified: &Table) -> usize {
    let compiled = build_compile_table(tcx, verified);
    let diffs = diff_tables(verified, &compiled);
    let sm = tcx.sess.source_map();
    // VERUS_CHECK_ERASURE_DUMP=1 prints both tables (to debug a reported difference)
    if std::env::var("VERUS_CHECK_ERASURE_DUMP").is_ok() {
        dump_table(sm, "verified", verified);
        dump_table(sm, "compiled", &compiled);
    }
    for d in &diffs {
        let via = if d.loc.via.is_empty() {
            String::new()
        } else {
            format!(" [in the macro expansion {}]", d.loc.via)
        };
        let msg = format!(
            "erasure check: the compiled program differs from the verified program: {}{via}",
            d.msg
        );
        match span_of_loc(sm, &d.loc) {
            Some(span) => {
                tcx.dcx().struct_span_err(span, msg).emit();
            }
            None => {
                tcx.dcx().struct_err(format!("{msg} (at {})", loc_to_string(sm, &d.loc))).emit();
            }
        }
    }
    diffs.len()
}

fn dump_table(sm: &SourceMap, which: &str, t: &Table) {
    for b in &t.bodies {
        eprintln!("== {which} body {} {:?}", b.owner, b.key);
        for ((loc, class), facts) in &b.nodes {
            for f in facts {
                eprintln!(
                    "   {} [{}-{}] {class} {:?}: {}{}",
                    loc_to_string(sm, loc),
                    loc.lo,
                    loc.hi,
                    f.kind,
                    f.cmp,
                    if f.one_sided { " (one-sided)" } else { "" }
                );
            }
        }
    }
}
