//! This module transforms the original code (with exec + proof + spec code)
//! into an abstracted version of the code (with only exec + proof code, no spec code)
//! for the purpose of checking ownership/lifetime/borrow on the exec and proof code.
//! (All spec code is erased because no ownership/lifetime/borrow checking should be
//! performed on spec code.)
//! This module then feeds the transformed code to rustc so that rustc can
//! catch any ownership/lifetime/borrow errors.

/*
The generated abstracted code discards much of the detail of the original code,
but keeps enough for ownership/lifetime/borrow checking.
Specifically it keeps:
- struct and enum declarations, and fields of the declarations
- lifetime ('a) and type (A) parameters, but not trait bounds (except for Copy, which is kept)
- functions, with impl methods turned into to top-level functions
- function bodies, but with external_body function bodies replaced with panic
  (external functions are erased completely)
- overall structure of blocks, statements, and expressions, but with specific operators
  transformed into calls to a generic function named "op"
- variable declarations and pattern matching
(The exact program elements that are kept can be seen in the abstract syntax defined in lifetime_ast.rs.)
For example, if the original code is the following:

    struct S {
    }

    spec fn fspec(i: u32, s1: S, s2: S) -> u32 {
        i
    }

    proof fn fproof(i: u32, tracked s1: S, tracked s2: S) -> u32 {
        i
    }

    fn fexec(i: u32, s1: S, s2: S) -> u32 {
        i
    }

    proof fn test_proof(i: u32, tracked s: S) {
        let j = fspec(i, s, s);
        let k = fproof(i, s, s);
    }

    fn test_exec(i: u32, s: S)
        requires i < 100
    {
        proof {
            let j = fspec(i, s, s);
            let k = fproof(i, s, s);
        }
        let k = fexec(i, s, s);
        let n = fexec(i, s, s);
    }

Then the generated "synthetic" Rust code will look like the following
(use the --log-all or --log-lifetime options to print the generated synthetic code
to a file in the .verus-log directory):

    struct D1_S {
    }

    fn f3_fproof(
        x4_i: (),
        x5_s1: D1_S,
        x6_s2: D1_S,
    )
    {
    }

    fn f8_fexec(
        x4_i: u32,
        x5_s1: D1_S,
        x6_s2: D1_S,
    ) -> u32
    {
        x4_i
    }

    fn f11_test_proof(
        x4_i: (),
        x9_s: D1_S,
    )
    {
        f3_fproof(op::<_, ()>(()), x9_s, x9_s, );
    }

    fn f15_test_exec(
        x4_i: u32,
        x9_s: D1_S,
    )
    {
        {
            f3_fproof(op::<_, ()>(()), x9_s, x9_s, );
        };
        let x12_k: u32 = f8_fexec(x4_i, x9_s, x9_s, );
        let x13_n: u32 = f8_fexec(x4_i, x9_s, x9_s, );
    }

When rustc is called on this generated code, rustc will report ownership violations
because the code tries to duplicate the linear variable "x9_s", which
corresponds to "s" in the original code.

When we print the error messages, we need to transform the line and column numbers
so that the error messages correspond to the original code.
These error messages are generated by running rustc on the synthetic code,
with rustc configured to generate errors in JSON format, capturing the JSON errors
and parsing them to retrieve the line/column information and error messages,
converting the synthetic line/column information back into spans for the original source code,
and then sending the error messages and spans to the rustc diagnostics for the original source code.
*/

// In functions executed through the lifetime rustc driver, use `ldbg!` for debug output.

use crate::erase::ErasureHints;
use crate::external::CrateItems;
use crate::lifetime_emit::*;
use crate::lifetime_generate::*;
use crate::spans::SpanContext;
use crate::util::error;
use crate::verus_items::VerusItems;
use rustc_hir::{AssocItemKind, Crate, ItemKind, MaybeOwner, OwnerNode};
use rustc_middle::ty::TyCtxt;
use serde::Deserialize;
use std::fs::File;
use std::io::Write;
use std::sync::Arc;
use vir::ast::VirErr;
use vir::messages::{Message, MessageLevel, message_bare};

const LDBG_PREFIX: &str = "!!!ldbg!!! ";

#[allow(unused)]
fn ldbg_prefix_all_lines(s: String) -> String {
    let mut s2 = s.lines().map(|l| LDBG_PREFIX.to_string() + l).fold(
        String::with_capacity(s.len()),
        |mut acc, l| {
            acc += &l;
            acc += "\n";
            acc
        },
    );
    s2.pop().unwrap();
    s2
}

// Derived from rust's std::dbg!
#[macro_export]
macro_rules! ldbg {
    // NOTE: We cannot use `concat!` to make a static string as a format argument
    // of `eprintln!` because `file!` could contain a `{` or
    // `$val` expression could be a block (`{ .. }`), in which case the `eprintln!`
    // will be malformed.
    () => {
        ::std::eprintln!("{}[lifetime {}:{}]", LDBG_PREFIX, $crate::file!(), $crate::line!())
    };
    ($val:expr $(,)?) => {
        // Use of `match` here is intentional because it affects the lifetimes
        // of temporaries - https://stackoverflow.com/a/48732525/1063961
        match $val {
            tmp => {
                let __string = ::std::format!("[lifetime {}:{}] {} = {:#?}", ::std::file!(), ::std::line!(), ::std::stringify!($val), &tmp);
                ::std::eprintln!("{}", $crate::lifetime::ldbg_prefix_all_lines(__string));
                tmp
            }
        }
    };
    ($($val:expr),+ $(,)?) => {
        ($(ldbg!($val)),+,)
    };
}

// Call Rust's mir_borrowck to check lifetimes of #[spec] and #[proof] code and variables
pub(crate) fn check<'tcx>(tcx: TyCtxt<'tcx>) {
    let krate = tcx.hir_crate(());
    rustc_hir_analysis::check_crate(tcx);
    if tcx.dcx().err_count() != 0 {
        return;
    }
    for owner in &krate.owners {
        if let MaybeOwner::Owner(owner) = owner {
            match owner.node() {
                OwnerNode::Item(item) => match &item.kind {
                    rustc_hir::ItemKind::Fn { .. } => {
                        tcx.ensure_ok().mir_borrowck(item.owner_id.def_id); // REVIEW(main_new) correct?
                    }
                    ItemKind::Impl(impll) => {
                        for item in impll.items {
                            match item.kind {
                                AssocItemKind::Fn { .. } => {
                                    tcx.ensure_ok().mir_borrowck(item.id.owner_id.def_id); // REVIEW(main_new) correct?
                                }
                                _ => {}
                            }
                        }
                    }
                    _ => (),
                },
                _ => {}
            }
        }
    }
}

const PROOF_FN_ONCE: u8 = 1;
const PROOF_FN_MUT: u8 = 2;
const PROOF_FN: u8 = 3;
const PROOF_FN_COPY: u8 = 4;
const PROOF_FN_SEND: u8 = 5;
const PROOF_FN_SYNC: u8 = 6;

const PRELUDE: &str = "\
#![feature(negative_impls)]
#![feature(with_negative_coherence)]
#![feature(box_patterns)]
#![feature(ptr_metadata)]
#![feature(never_type)]
#![feature(allocator_api)]
#![feature(unboxed_closures)]
#![feature(fn_traits)]
#![feature(tuple_trait)]
#![feature(f16)]
#![feature(f128)]
#![allow(non_camel_case_types)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(unused_assignments)]
#![allow(unreachable_patterns)]
#![allow(unused_parens)]
#![allow(unused_braces)]
#![allow(dead_code)]
#![allow(unreachable_code)]
#![allow(unconditional_recursion)]
#![allow(unused_mut)]
#![allow(unused_labels)]
use std::marker::PhantomData;
use std::marker::Tuple;
use std::rc::Rc;
use std::sync::Arc;
use std::alloc::Allocator;
use std::alloc::Global;
use std::mem::ManuallyDrop;
use std::ptr::Pointee;
use std::ptr::Thin;
fn op<A, B>(a: A) -> B { panic!() }
fn static_ref<T>(t: T) -> &'static T { panic!() }
fn tracked_new<T>(t: T) -> Tracked<T> { panic!() }
fn tracked_exec_borrow<'a, T>(t: &'a T) -> &'a Tracked<T> { panic!() }
fn clone<T>(t: &T) -> T { panic!() }
fn rc_new<T>(t: T) -> std::rc::Rc<T> { panic!() }
fn arc_new<T>(t: T) -> std::sync::Arc<T> { panic!() }
fn box_new<T>(t: T) -> Box<T> { panic!() }
struct Tracked<A> { a: PhantomData<A> }
impl<A> Tracked<A> {
    pub fn get(self) -> A { panic!() }
    pub fn borrow(&self) -> &A { panic!() }
    pub fn borrow_mut(&mut self) -> &mut A { panic!() }
}
struct Ghost<A> { a: PhantomData<A> }
impl<A> Clone for Ghost<A> { fn clone(&self) -> Self { panic!() } }
impl<A> Copy for Ghost<A> { }
impl<A: Copy> Clone for Tracked<A> { fn clone(&self) -> Self { panic!() } }
impl<A: Copy> Copy for Tracked<A> { }
#[derive(Clone, Copy)] struct int;
#[derive(Clone, Copy)] struct nat;
struct FnSpec<Args, Output> { x: PhantomData<(Args, Output)> }
struct InvariantBlockGuard;
fn open_atomic_invariant_begin<'a, X, V>(_inv: &'a X) -> (InvariantBlockGuard, V) { panic!(); }
fn open_local_invariant_begin<'a, X, V>(_inv: &'a X) -> (InvariantBlockGuard, V) { panic!(); }
fn open_invariant_end<V>(_guard: InvariantBlockGuard, _v: V) { panic!() }
fn index<'a, V, Idx, Output>(v: &'a V, index: Idx) -> &'a Output { panic!() }
trait IndexSet{
fn index_set<Idx, V>(&mut self, index: Idx, val: V) { panic!() }
}
impl<A:?Sized> IndexSet for A {}
struct C<const N: usize, A: ?Sized>(Box<A>);
struct Arr<A: ?Sized, const N: usize>(Box<A>);
fn use_type_invariant<A>(a: A) -> A { a }

struct FnProof<'a, P, M, N, A, O>(PhantomData<P>, PhantomData<M>, PhantomData<N>, PhantomData<&'a fn(A) -> O>);
struct FOpts<const B: u8, C, const D: u8, const E: u8, const G: u8>(PhantomData<C>);
trait ProofFnOnce {}
trait ProofFnMut: ProofFnOnce {}
trait ProofFn: ProofFnMut {}
struct ProofFnConfirm;
trait ConfirmCopy<const D: u8, F> {}
trait ConfirmUsage<A, O, const B: u8, F> {}
impl<const B: u8, C, const E: u8, const G: u8> Clone for FOpts<B, C, (PROOF_FN_COPY), E, G> { fn clone(&self) -> Self { panic!() } }
impl<const B: u8, C, const E: u8, const G: u8> Copy for FOpts<B, C, (PROOF_FN_COPY), E, G> {}
impl<const B: u8, C, const D: u8, const E: u8, const G: u8> ProofFnOnce for FOpts<B, C, D, E, G> {}
impl<C, const D: u8, const E: u8, const G: u8> ProofFnMut for FOpts<(PROOF_FN_MUT), C, D, E, G> {}
impl<C, const D: u8, const E: u8, const G: u8> ProofFnMut for FOpts<(PROOF_FN), C, D, E, G> {}
impl<C, const D: u8, const E: u8, const G: u8> ProofFn for FOpts<(PROOF_FN), C, D, E, G> {}
impl<'a, P: Copy, M, N, A, O> Clone for FnProof<'a, P, M, N, A, O> { fn clone(&self) -> Self { panic!() } }
impl<'a, P: Copy, M, N, A, O> Copy for FnProof<'a, P, M, N, A, O> {}
impl<'a, P: ProofFnOnce, M, N, A: Tuple, O> FnOnce<A> for FnProof<'a, P, M, N, A, O> {
    type Output = O;
    extern \"rust-call\" fn call_once(self, _: A) -> <Self as FnOnce<A>>::Output { panic!() }
}
impl<'a, P: ProofFnMut, M, N, A: Tuple, O> FnMut<A> for FnProof<'a, P, M, N, A, O> {
    extern \"rust-call\" fn call_mut(&mut self, _: A) -> <Self as FnOnce<A>>::Output { panic!() }
}
impl<'a, P: ProofFn, M, N, A: Tuple, O> Fn<A> for FnProof<'a, P, M, N, A, O> {
    extern \"rust-call\" fn call(&self, _: A) -> <Self as FnOnce<A>>::Output { panic!() }
}
impl<F: Copy> ConfirmCopy<(PROOF_FN_COPY), F> for ProofFnConfirm {}
impl<F> ConfirmCopy<0, F> for ProofFnConfirm {}
impl<A: Tuple, O, F: FnOnce<A, Output = O>> ConfirmUsage<A, O, (PROOF_FN_ONCE), F> for ProofFnConfirm {}
impl<A: Tuple, O, F: FnMut<A, Output = O>> ConfirmUsage<A, O, (PROOF_FN_MUT), F> for ProofFnConfirm {}
impl<A: Tuple, O, F: Fn<A, Output = O>> ConfirmUsage<A, O, (PROOF_FN), F> for ProofFnConfirm {}
pub fn closure_to_fn_proof<'a, const B: u8, const D: u8, const E: u8, const G: u8, M, N, A, O, F: 'a>(_f: F) -> FnProof<'a, FOpts<B, (), D, E, G>, M, N, A, O>
where ProofFnConfirm: ConfirmUsage<A, O, B, F>, ProofFnConfirm: ConfirmCopy<D, F>, M: Tuple, A: Tuple,
{ panic!() }

fn main() {}
";

fn emit_check_tracked_lifetimes<'tcx>(
    cmd_line_args: crate::config::Args,
    tcx: TyCtxt<'tcx>,
    verus_items: std::sync::Arc<VerusItems>,
    spans: &SpanContext,
    krate: &'tcx Crate<'tcx>,
    emit_state: &mut EmitState,
    erasure_hints: &ErasureHints,
    item_to_module_map: &CrateItems,
    vir_crate: &vir::ast::Krate,
) -> State {
    let mut gen_state = if cmd_line_args.new_lifetime {
        crate::lifetime_generate::State::new()
    } else {
        crate::lifetime_generate::gen_check_tracked_lifetimes(
            cmd_line_args,
            tcx,
            verus_items,
            krate,
            erasure_hints,
            item_to_module_map,
        )
    };
    crate::trait_conflicts::gen_check_trait_impl_conflicts(spans, vir_crate, &mut gen_state);

    let prelude = PRELUDE
        .replace("(PROOF_FN_ONCE)", &PROOF_FN_ONCE.to_string())
        .replace("(PROOF_FN_MUT)", &PROOF_FN_MUT.to_string())
        .replace("(PROOF_FN)", &PROOF_FN.to_string())
        .replace("(PROOF_FN_COPY)", &PROOF_FN_COPY.to_string())
        .replace("(PROOF_FN_SEND)", &PROOF_FN_SEND.to_string())
        .replace("(PROOF_FN_SYNC)", &PROOF_FN_SYNC.to_string());
    for line in prelude.split('\n') {
        emit_state.writeln(line.replace("\r", ""));
    }

    for t in gen_state.trait_decls.iter() {
        emit_trait_decl(emit_state, t);
    }
    for d in gen_state.datatype_decls.iter() {
        emit_datatype_decl(emit_state, d);
    }
    for t in gen_state.trait_impls.iter() {
        emit_trait_impl(emit_state, t);
    }
    for f in gen_state.fun_decls.iter() {
        emit_fun_decl(emit_state, f);
    }
    gen_state
}

struct LifetimeCallbacks {
    code: String,
}

impl rustc_driver::Callbacks for LifetimeCallbacks {
    // note: we only need to call into config here,
    // to change the file_loader
    fn config<'tcx>(&mut self, cfg: &mut rustc_interface::interface::Config) {
        cfg.file_loader = Some(Box::new(LifetimeFileLoader { rust_code: self.code.clone() }));
    }

    fn after_expansion<'tcx>(
        &mut self,
        _compiler: &rustc_interface::interface::Compiler,
        queries: TyCtxt<'tcx>,
    ) -> rustc_driver::Compilation {
        check(queries);
        rustc_driver::Compilation::Stop
    }
}

struct LifetimeFileLoader {
    rust_code: String,
}

impl LifetimeFileLoader {
    const FILENAME: &'static str = "dummyrs.rs";
}

impl rustc_span::source_map::FileLoader for LifetimeFileLoader {
    fn file_exists(&self, _path: &std::path::Path) -> bool {
        panic!("unexpected call to file_exists")
    }

    fn read_file(&self, path: &std::path::Path) -> Result<String, std::io::Error> {
        assert!(path.display().to_string() == Self::FILENAME.to_string());
        Ok(self.rust_code.clone())
    }

    fn read_binary_file(&self, path: &std::path::Path) -> Result<Arc<[u8]>, std::io::Error> {
        assert!(path.display().to_string() == Self::FILENAME.to_string());
        Ok(self.rust_code.as_bytes().into())
    }
}

#[derive(Debug, Deserialize)]
struct DiagnosticSpan {
    line_start: usize,
    line_end: usize,
    column_start: usize,
    column_end: usize,
}

#[derive(Debug, Deserialize)]
struct Diagnostic {
    message: String,
    level: String,
    spans: Vec<DiagnosticSpan>,
    rendered: Option<String>,
}

pub const LIFETIME_DRIVER_ARG: &'static str = "--internal-lifetime-driver";

pub fn lifetime_rustc_driver(rustc_args: &[String], rust_code: String) {
    let mut callbacks = LifetimeCallbacks { code: rust_code };
    rustc_driver::run_compiler(rustc_args, &mut callbacks)
}

pub(crate) fn check_tracked_lifetimes<'tcx>(
    cmd_line_args: crate::config::Args,
    tcx: TyCtxt<'tcx>,
    verus_items: std::sync::Arc<VerusItems>,
    spans: &SpanContext,
    erasure_hints: &ErasureHints,
    item_to_module_map: &CrateItems,
    vir_crate: &vir::ast::Krate,
    lifetime_log_file: Option<File>,
) -> Result<Vec<Message>, VirErr> {
    let krate = tcx.hir_crate(());
    let mut emit_state = EmitState::new();
    let gen_state = emit_check_tracked_lifetimes(
        cmd_line_args,
        tcx,
        verus_items,
        spans,
        krate,
        &mut emit_state,
        erasure_hints,
        item_to_module_map,
        vir_crate,
    );
    let mut rust_code: String = String::new();
    for line in &emit_state.lines {
        rust_code.push_str(&line.text);
        rust_code.push('\n');
    }
    if let Some(mut file) = lifetime_log_file {
        write!(file, "{}", &rust_code).expect("error writing to lifetime log file");
    }
    let rustc_args = vec![LIFETIME_DRIVER_ARG, LifetimeFileLoader::FILENAME, "--error-format=json"];

    let mut child = std::process::Command::new(std::env::current_exe().unwrap())
        // avoid warning about jobserver fd
        .env_remove("CARGO_MAKEFLAGS")
        .args(&rustc_args[..])
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .expect("could not execute lifetime rustc process");
    let mut child_stdin = child.stdin.take().expect("take stdin");
    // std::fs::write("/tmp/verus_lifetime_generate.rs", rust_code.clone()).unwrap();
    child_stdin.write(rust_code.as_bytes()).expect("failed to send code to lifetime rustc");
    std::mem::drop(child_stdin);
    let run = child.wait_with_output().expect("lifetime rustc wait failed");
    let rust_output = std::str::from_utf8(&run.stderr[..]).unwrap().trim();
    let mut msgs: Vec<Message> = Vec::new();
    let debug = false;
    if rust_output.len() > 0 {
        for ss in rust_output.split("\n") {
            if let Some(ss) = ss.strip_prefix(LDBG_PREFIX) {
                eprintln!("{}", ss);
            } else {
                let diag: Diagnostic = serde_json::from_str(ss).expect("serde_json from_str");
                if diag.level == "failure-note" {
                    continue;
                }
                if diag.level == "warning" {
                    dbg!("internal error: unexpected warning");
                    dbg!(diag);
                    continue;
                }
                assert!(diag.level == "error");
                let msg_text = gen_state.unmangle_names(&diag.message);
                let mut msg = message_bare(MessageLevel::Error, &msg_text);
                if debug {
                    dbg!(&msg);
                }
                use std::collections::HashSet;
                let mut missing_span = diag.spans.len() == 0;
                let mut missing_span_line_seqs: HashSet<(usize, usize)> = HashSet::new();
                for dspan in &diag.spans {
                    if debug {
                        dbg!(&dspan);
                    }
                    let span = emit_state.get_span(
                        dspan.line_start - 1,
                        dspan.column_start - 1,
                        dspan.line_end - 1,
                        dspan.column_end - 1,
                    );
                    if let Some(span) = span {
                        msg = msg.primary_span(&spans.to_air_span(span));
                    } else {
                        eprintln!(
                            "note: could not find span associated with error message; printing raw error message instead"
                        );
                        missing_span = true;
                        let mut l1 = dspan.line_start - 1;
                        let mut l2 = dspan.line_end - 1;
                        while l1 > 0 && !emit_state.lines[l1].start_of_decl {
                            l1 -= 1;
                        }
                        while l2 + 1 < emit_state.lines.len() && !emit_state.lines[l2].start_of_decl
                        {
                            l2 += 1;
                        }
                        if !missing_span_line_seqs.contains(&(l1, l2)) {
                            for i in l1..=l2 {
                                eprintln!("{}", &emit_state.lines[i].text);
                            }
                            missing_span_line_seqs.insert((l1, l2));
                        }
                    }
                }
                if missing_span {
                    eprintln!("{}", &diag.rendered.unwrap());
                }
                msgs.push(msg);
            }
        }
    }
    if debug {
        dbg!(msgs.len());
    }
    if msgs.len() == 0 && !run.status.success() {
        Err(error("lifetime checking failed"))
    } else {
        Ok(msgs)
    }
}
