[package]
name = "veritas-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.18"
chrono = "0.4"
yansi = "1.0"
sha2 = "0.10"
base64 = "0.22"
serde = { version = "1.0", features = ["std", "derive"] }
getopts = "0.2"
toml = "0.8"
regex = "1.10.4"
serde_json = "1.0.116"
