name: ci

on:
  workflow_dispatch:

  merge_group:

  pull_request:
    types: [opened, synchronize, reopened]

# Cancel a workflow iff the branch for the pull request got updated
#
# How:
#   - This creates a concurrency group for workflow runs;
#   - When the workflow runs, it cancels in-progress runs if the concurrency group is the same
#   - The group names are ci-<pr number> (in the case of PRs) and ci-<SHA> for main
#   - This means that we still run CI for every commit on main (but those runs don't get updated anyway)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.push.after }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  # check if formatting is correct
  fmt:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.95.0

      - name: setup verusfmt
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/verus-lang/verusfmt/releases/latest/download/verusfmt-installer.sh | sh

      - name: check rustfmt/verusfmt
        working-directory: ./source
        run: |
          . ../tools/activate
          vargo fmt -- --check

      - name: check cargo fmt for vargo
        working-directory: ./tools/vargo
        run: cargo fmt -- --check

  # run linter (clippy)
  clippy:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.95.0
          components: clippy

      - name: clippy check codebase
        working-directory: ./source
        run: |
          . ../tools/activate
          vargo clippy -- -D warnings

      - name: clippy check vargo
        working-directory: ./tools/vargo
        run: cargo clippy -- -D warnings

  # detect whether subprojects (e.g. cargo-verus) changed
  change_filter:
    runs-on: ubuntu-22.04
    outputs:
      cargo_verus: ${{ steps.filter.outputs.cargo_verus }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: detect changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            cargo_verus:
              - 'source/cargo-verus/**'

  # run cargo-verus tests
  cargo-verus-test:
    needs: [fmt, clippy, change_filter]
    runs-on: ubuntu-22.04
    steps:
      - name: check for cargo-verus changes
        if: needs.change_filter.outputs.cargo_verus != 'true'
        run: echo "No source/cargo-verus changes detected; skipping cargo-verus tests."

      - name: checkout
        if: needs.change_filter.outputs.cargo_verus == 'true'
        uses: actions/checkout@v4

      - name: setup rust
        if: needs.change_filter.outputs.cargo_verus == 'true'
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.95.0

      - name: cargo-verus tests
        if: needs.change_filter.outputs.cargo_verus == 'true'
        working-directory: ./source
        run: cargo test -p cargo-verus

  # check if it builds and runs on macos, running the full test suite
  # (in release mode because it makes a huge difference)
  full-test:
    runs-on: macos-14

    defaults:
      run:
        shell: bash

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: get z3
        working-directory: ./source
        run: |
          ./tools/get-z3.sh
          echo z3 version `./z3 --version`

      - name: get cvc5
        working-directory: ./source
        run: |
          ./tools/get-cvc5.sh
          echo cvc5 version `./cvc5 --version`

      - name: setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.95.0

      - name: setup nextest
        uses: taiki-e/install-action@nextest

      - name: build
        working-directory: ./source
        run: |
          . ../tools/activate
          vargo clean
          RUSTFLAGS="-C debug-assertions" vargo build --release

      - name: full tests
        working-directory: ./source
        run: |
          . ../tools/activate
          RUSTFLAGS="-C debug-assertions" VERUS_Z3_PATH="$(pwd)/z3" vargo nextest run --release -p air
          RUSTFLAGS="-C debug-assertions" VERUS_Z3_PATH="$(pwd)/z3" vargo nextest run --release -p rust_verify_test
          # check cvc5
          vargo run --release -p rust_verify -- -V cvc5 ../examples/assorted_demo.rs

      - name: build line-count tool
        working-directory: ./source/tools/line_count
        run: cargo build

  # check if it builds and that basic tests pass on our main supported platforms
  basic-test:
    strategy:
      matrix:
        build: [macos-x86_64, linux, windows]
        include:
          - build: macos-x86_64
            os: macos-15-intel
          - build: linux
            os: ubuntu-22.04
          - build: windows
            os: windows-2022

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: get z3
        working-directory: ./source
        run: |
          ./tools/get-z3.sh
          echo z3 version `./z3 --version`

      - name: setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.95.0

      - name: setup nextest
        uses: taiki-e/install-action@nextest

      - name: build
        working-directory: ./source
        run: |
          . ../tools/activate
          vargo clean
          vargo build

      - name: basic tests
        working-directory: ./source
        run: |
          . ../tools/activate
          VERUS_Z3_PATH="$(pwd)/z3" vargo nextest run -p rust_verify_test --test basic

      - name: build line-count tool
        working-directory: ./source/tools/line_count
        run: cargo build

  # check if esoteric conficurations build
  smoke-test:
    strategy:
      matrix:
        features: [record-history, no-std, no-alloc, singular]

    runs-on: macos-14

    defaults:
      run:
        shell: bash

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: get z3
        working-directory: ./source
        run: |
          ./tools/get-z3.sh
          echo z3 version `./z3 --version`

      - name: setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.95.0

      - name: setup nextest
        uses: taiki-e/install-action@nextest

      - name: download singular
        if: matrix.features == 'singular'
        run: curl -fLO https://github.com/verus-lang/verus/releases/download/dependency/singular-4.3.2/Singular-4-3-2_M1.dmg

      - name: build
        working-directory: ./source
        run: |
          . ../tools/activate
          vargo clean

          case "${{ matrix.features }}" in
            "singular")
              hdiutil attach ../Singular-4-3-2_M1.dmg
              DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/Volumes/Singular4.3.2/Singular.app/Contents/lib VERUS_SINGULAR_PATH=/Volumes/Singular4.3.2/Singular.app/Contents/bin/Singular VERUS_Z3_PATH="$(pwd)/z3" vargo build --features singular
              ;;
            "record-history")
              vargo build --features record-history
              ;;
            "no-std")
              vargo build --vstd-no-std
              cd vstd
              unset -f cargo
              cargo build --no-default-features --features alloc
              ;;
            "no-alloc")
              vargo build --vstd-no-std --vstd-no-alloc
              cd vstd
              unset -f cargo
              cargo build --no-default-features
              ;;
          esac

      - name: smoke test
        working-directory: ./source
        run: |
          . ../tools/activate

          case "${{ matrix.features }}" in
            "singular")
              hdiutil attach ../Singular-4-3-2_M1.dmg
              DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/Volumes/Singular4.3.2/Singular.app/Contents/lib VERUS_SINGULAR_PATH=/Volumes/Singular4.3.2/Singular.app/Contents/bin/Singular VERUS_Z3_PATH="$(pwd)/z3" vargo nextest run -p air --features singular
              DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/Volumes/Singular4.3.2/Singular.app/Contents/lib VERUS_SINGULAR_PATH=/Volumes/Singular4.3.2/Singular.app/Contents/bin/Singular VERUS_Z3_PATH="$(pwd)/z3" vargo nextest run -p rust_verify_test --features singular --test integer_ring
              DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/Volumes/Singular4.3.2/Singular.app/Contents/lib VERUS_SINGULAR_PATH=/Volumes/Singular4.3.2/Singular.app/Contents/bin/Singular VERUS_Z3_PATH="$(pwd)/z3" vargo nextest run -p rust_verify_test --features singular --test examples -- examples_integer_ring
              ;;
            "record-history")
              VERUS_Z3_PATH="$(pwd)/z3" vargo nextest run -p rust_verify_test --features record-history --test basic
              ;;
          esac

  # build the documentation
  # will complain if there are warnings
  build-docs:
    needs: [fmt, clippy]
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.95.0

      - name: build docs
        working-directory: ./source
        run: |
          . ../tools/activate
          ./tools/get-z3.sh
          ./tools/docs.sh --strict # strict will complain if there are warnings
