name: pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Cancel previous pages workflows if a new one comes in
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  MDBOOK_VERSION: 0.5.2

jobs:
  build:
    if: github.repository == 'verus-lang/verus'
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.95.0

      - name: build verusdoc
        working-directory: ./source
        run: |
          . ../tools/activate
          ./tools/get-z3.sh
          ./tools/docs.sh --strict

      - name: setup dir structure
        run: |
          mkdir -p ./_site/guide
          mkdir -p ./_site/state_machines

      - name: setup mdbook
        run: |
          curl -L "https://github.com/rust-lang/mdBook/releases/download/v${MDBOOK_VERSION}/mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz" > mdbook.tar.gz
          tar -xvf mdbook.tar.gz
          rm mdbook.tar.gz
          chmod +x mdbook

      - name: build guide book
        run: ./mdbook build -d ./_site/guide source/docs/guide

      - name: build state_machines book
        run: ./mdbook build -d ./_site/state_machines source/docs/state_machines

      - name: copy verusdoc into site
        run: cp -R source/doc ./_site/verusdoc

      - name: add publications and projects page
        uses: actions/jekyll-build-pages@v1
        with:
          source: source/docs/publications-and-projects
          destination: ./_site/publications-and-projects

      - name: add verus pages
        uses: actions/jekyll-build-pages@v1
        with:
          source: source/docs/verus
          destination: ./_site/verus

      - name: upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4
